import { useState, useEffect, useRef, useMemo, useCallback } from "react";

const REDES = ["Instagram Feed","Instagram Stories","Instagram Reels","Facebook","TikTok","X","YouTube Shorts","YouTube"];
const PILARES = ["P1 – Curaduría","P2 – Planes","P3 – Experiencia","P4 – Servicio","P5 – Prueba social","P6 – Cultura"];
const FORMATOS = ["Post estático","Carrusel","Reel","Reel corto","Story interactiva","Story estática","Story","Video","YouTube Short","Live"];
const ESTADOS = ["Pendiente","En producción","Publicado"];
const DIAS_SEMANA = ["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"];
const ADMIN_PASS = "Teatrando2026Amaya";

const TIPO_COLOR = {"RESENA":"#7c3aed","3 RAZONES":"#0891b2","5 RAZONES":"#0891b2","FRASE":"#b45309","RECOMENDACION":"#059669","ESTRENO":"#dc2626","SI TE GUSTO":"#be185d","MUNDIAL":"#d97706","VACACIONES":"#0e7490"};
const PILAR_COLOR = {"P1 – Curaduría":"#C40803","P2 – Planes":"#8B0000","P3 – Experiencia":"#B61220","P4 – Servicio":"#1a1a2e","P5 – Prueba social":"#0d2137","P6 – Cultura":"#700B15"};
const RED_ICON = {"Instagram Feed":"📸","Instagram Stories":"📲","Instagram Reels":"🎬","Facebook":"👍","TikTok":"🎵","X":"✖","YouTube Shorts":"▶","YouTube":"🎥"};
const RED_COLOR = {"Instagram Feed":"#E1306C","Instagram Stories":"#833AB4","Instagram Reels":"#405DE6","Facebook":"#1877F2","TikTok":"#ff0050","X":"#ffffff","YouTube Shorts":"#FF0000","YouTube":"#FF0000"};
const ESTADO_CFG = {"Pendiente":{color:"#f59e0b",bg:"#2a1f00"},"En producción":{color:"#3b82f6",bg:"#001a2a"},"Publicado":{color:"#22c55e",bg:"#002a10"}};

const mkId = (pfx) => `${pfx}_${Date.now()}_${Math.random().toString(36).slice(2,6)}`;
const buildPub = (o={}) => ({id:mkId("p"),fecha:"",dia:"",mes:"Julio",semana:1,pub:1,redes:["Instagram Feed","Facebook"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"",tema:"",copy:"",cta:"Link en bio",estado:"Pendiente",notas:"",linkDiseno:"",disenho:"",...o});
const buildResena = (o={}) => ({id:mkId("r"),semana:1,obra:"",titulo:"",...o});

let _historial = [];
const regCambio = (id,campo,ant,nuevo) => {
  _historial = [{ts:new Date().toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit",second:"2-digit"}),id,campo,anterior:typeof ant==="object"?JSON.stringify(ant):String(ant),nuevo:typeof nuevo==="object"?JSON.stringify(nuevo):String(nuevo)},..._historial].slice(0,300);
  return [..._historial];
};
const buildJulio = () => [
// ── SEMANA 1: 1-5 julio ──
{id:"jul_s1_01",fecha:"Mar 1",dia:"Martes",mes:"Julio",semana:1,pub:1,redes:["Instagram Feed","Facebook","X"],pilar:"P4 – Servicio",formato:"Post estático",tipo:"MUNDIAL",tema:"Alerta promoción El Día que México Ganó el Mundial, boletos $450",copy:"🚨 ALERTA PROMOCIÓN\n\nEl día que México ganó el Mundial llegó al teatro.\nY los boletos están a $450.\n\nSí. Leíste bien.\n\n🎟️ Consíguelos en teatrando.com.mx antes de que se agoten.\n\n#Teatrando #TeatroCDMX #Promocion #Mundial2026 #QueHacerEnCDMX",estado:"Publicado",notas:"YA PUBLICADO",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s1_02",fecha:"Mar 1",dia:"Martes",mes:"Julio",semana:1,pub:2,redes:["Instagram Stories"],pilar:"P3 – Experiencia",formato:"Story estática",tipo:"",tema:"Archivo Confidencial",copy:"📁 ARCHIVO CONFIDENCIAL\n\nUn expediente que no debería existir.\nUna historia que no puedes perderte.\n\n🎟️ teatrando.com.mx",estado:"Publicado",notas:"YA PUBLICADO",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s1_03",fecha:"Mié 2",dia:"Miércoles",mes:"Julio",semana:1,pub:1,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P1 – Curaduría",formato:"Reel",tipo:"",tema:"Dani y el Profundo Mar Azul, última función",copy:"Hoy es la última función de Dani y el Profundo Mar Azul. 🌊🎭\n\nSi no la has visto — esta es tu última oportunidad.\nSi ya la viste — ya sabes por qué te duele que termine.\n\nHasta siempre, Dani.\n\n📍 La Teatrería · Hoy\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #UltimaFuncion #ObrasDeCDMX",estado:"Publicado",notas:"YA PUBLICADO",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s1_04",fecha:"Mié 2",dia:"Miércoles",mes:"Julio",semana:1,pub:2,redes:["Instagram Stories"],pilar:"P4 – Servicio",formato:"Story estática",tipo:"",tema:"¿Cómo compro mis boletos en Teatrando?",copy:"¿Cómo compro mis boletos en Teatrando? 🎟️\n\n1️⃣ Entra a teatrando.com.mx\n2️⃣ Elige tu obra\n3️⃣ Selecciona fecha y función\n4️⃣ Paga seguro en línea\n5️⃣ Tu boleto llega a tu correo",estado:"Publicado",notas:"YA PUBLICADO",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s1_05",fecha:"Jue 3",dia:"Jueves",mes:"Julio",semana:1,pub:1,redes:["Instagram Stories"],pilar:"P5 – Prueba social",formato:"Story interactiva",tipo:"",tema:"Encuesta gana boletos El Pelón y Cómo te va mi amor",copy:"¿Cuál quieres ver? 🎭\n\n😂 El Pelón en sus tiempos del Cólera\n❤️ Cómo te va mi amor\n\n¡Vota y gana boletos!\n🎟️ teatrando.com.mx",estado:"Publicado",notas:"YA PUBLICADO",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s1_06",fecha:"Jue 3",dia:"Jueves",mes:"Julio",semana:1,pub:2,redes:["Instagram Stories"],pilar:"P1 – Curaduría",formato:"Story estática",tipo:"",tema:"Presentación nuevo actor Las Heridas del Viento",copy:"Nuevo integrante en Las Heridas del Viento. 🎭\n\nEl elenco se renueva — la historia sigue siendo igual de poderosa.\n\n📍 Teatro Milán · Martes 8:45pm\n🎟️ teatrando.com.mx",estado:"Publicado",notas:"YA PUBLICADO",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s1_07",fecha:"Sáb 4",dia:"Sábado",mes:"Julio",semana:1,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P7 – Turismo CDMX",formato:"Post estático",tipo:"MUNDIAL",tema:"Mañana juega México, esta noche el teatro te espera",copy:"Mañana juega México. ⚽🇲🇽\nPero esta noche CDMX tiene otro escenario listo para ti.\n\n🎭 SOMOS RAÍZ, SOMOS DANZA · Hoy 7pm · Teatro Varsovia\n💃 CARLOTA · Sáb 8pm · Castillo Chapultepec\n😂 SOR-PRESAS AMÉN · Sáb 6 y 8:30pm · Teatro Hidalgo\n🌹 PERFUME DE GARDENIA · Sáb 6 y 9:15pm · Teatro San Rafael\n😂 SOLTERA PERO NO PARA CUALQUIERA · Sáb 8:45pm · Foro Lenin\n\nEl partido dura 90 minutos.\nEl teatro te dura para siempre.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #Mundial2026 #MexicoEnElMundial #QueHacerEnCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s1_08",fecha:"Sáb 4",dia:"Sábado",mes:"Julio",semana:1,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P7 – Turismo CDMX",formato:"Carrusel",tipo:"",tema:"Si visitas CDMX para el Mundial, el teatro tiene que estar en tu lista",copy:"Si viniste a CDMX para el Mundial — escucha esto. 🌎🎭\n\nEsta ciudad no es solo estadios y fanfests.\nEs la capital teatral más grande de América Latina.\n\n5 razones para ir al teatro mientras estás aquí:\n\n🎭 Más de 200 recintos activos en toda la ciudad\n🎟️ Boletos desde $200 pesos — más barato que una camiseta del torneo\n🌟 Obras en cartelera que no existen en ningún otro lugar del mundo\n😱 Experiencias inmersivas que ningún partido puede darte\n❤️ La mejor manera de llevarte algo de CDMX que no cabe en la maleta\n\nDesliza y descubre por qué el teatro es el plan que no tenías contemplado.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #Mundial2026 #VisitaCDMX #QueHacerEnCDMX",estado:"Pendiente",notas:"Dirigido a visitantes del Mundial",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s1_09",fecha:"Dom 5",dia:"Domingo",mes:"Julio",semana:1,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P7 – Turismo CDMX",formato:"Post estático",tipo:"MUNDIAL",tema:"HOY JUEGA MÉXICO, el teatro también está abierto",copy:"HOY JUEGA MÉXICO. 🇲🇽⚽\nAntes del partido — o después de la celebración —\nel teatro también está listo para ti.\n\n🎭 CDMX no es solo sede de fútbol.\nEs la capital cultural más viva de América Latina.\n\n¿Ya tienes tu plan de teatro para hoy?\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #Mundial2026 #MexicoEnElMundial #CDMX",estado:"Pendiente",notas:"México juega hoy",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s1_10",fecha:"Dom 5",dia:"Domingo",mes:"Julio",semana:1,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"RESENA",tema:"Axolotl La Aventura del Cacao Perdido, el plan perfecto para este domingo familiar",copy:"El plan perfecto para este domingo en familia. 🌿🎭\n\n🫎 AXOLOTL LA AVENTURA DEL CACAO PERDIDO\n\nAventura, magia y mucho corazón en el escenario.\nIdeal para los más chicos — y los adultos que no quieren crecer.\n\n📍 Teatro Conjunto Carlos Pellicer\n🗓️ Dom 1pm · Hasta el 19 de julio\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroInfantil #TeatroCDMX #PlanFamiliar #ObrasDeCDMX",estado:"Pendiente",notas:"Funciones sáb y dom 1pm hasta el 19 julio",disenho:"",cta:"teatrando.com.mx"},
// ── SEMANA 2: 6-12 julio ──
{id:"jul_s2_01",fecha:"Lun 6",dia:"Lunes",mes:"Julio",semana:2,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P1 – Curaduría",formato:"Carrusel",tipo:"RECOMENDACION",tema:"El Sótano, Afterglow, Método de Gronholm y Perfume de Gardenia",copy:"LA RECOMENDACIÓN TEATRANDO DE ESTA SEMANA 🎭\n\n😱 EL SÓTANO\nLa experiencia que no se puede spoilear — solo vivir.\n📍 Teatro Fernando Soler · Vie 7 y 9:15pm · Sáb 6 y 8:30pm · Dom 5 y 7:30pm\n\n🎵 AFTERGLOW\nAntes de que cierre — esta obra tiene que estar en tu lista.\n📍 Teatro Milán · Vie 7 y 9pm · Sáb 6 y 8pm · Dom 7pm — HASTA EL 12\n\n🧠 MÉTODO DE GRONHOLM\nSuspenso corporativo. Nadie es lo que parece.\n📍 Teatro Xola · Vie 8pm · Sáb 7pm · Dom 6pm\n\n🌹 PERFUME DE GARDENIA\nGlamour, nostalgia y una voz que no se olvida.\n📍 Teatro San Rafael · Sáb 6 y 9:15pm · Dom 4:30pm\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #CarteleraCDMX #RecomendacionTeatrando",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s2_02",fecha:"Lun 6",dia:"Lunes",mes:"Julio",semana:2,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P6 – Cultura",formato:"Post estático",tipo:"MUNDIAL",tema:"Teatro mexicano y el Mundial, dos escenarios una misma pasión",copy:"Dos escenarios. Una misma pasión. 🎭⚽\n\nMéxico tiene una de las carteleras teatrales más grandes de América Latina.\nY también está en el Mundial.\n\nNo es coincidencia — es que los mexicanos sabemos vivir en grande:\nen la cancha y bajo los reflectores.\n\nEsta semana, CDMX es la ciudad más viva del planeta.\n¿Ya la estás viviendo completa?\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #Mundial2026 #CulturaTeatro #CDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s2_03",fecha:"Mar 7",dia:"Martes",mes:"Julio",semana:2,pub:1,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P4 – Servicio",formato:"Reel",tipo:"",tema:"Cómo comprar boletos en teatrando.com.mx",copy:"Comprar boletos de teatro nunca fue tan fácil. 🎟️🎭\n\nEntras a teatrando.com.mx\nEliges tu obra favorita\nSeleccionas fecha y función\nPagas seguro en línea\nY tu boleto llega directo a tu correo.\n\nSin filas. Sin complicaciones.\nCon los mejores descuentos de CDMX.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #BoletosDeTeatro #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s2_04",fecha:"Mar 7",dia:"Martes",mes:"Julio",semana:2,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P5 – Prueba social",formato:"Post estático",tipo:"FRASE",tema:"Frase de la semana",copy:"'El teatro es poesía que se sale del libro para hacerse humana.' 🎭✨\n— Federico García Lorca\n\nGuárdala y compártela con alguien que todavía no ha descubierto el teatro.\n\n#Teatrando #FraseDeTeatro #TeatroCDMX #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s2_05",fecha:"Mié 8",dia:"Miércoles",mes:"Julio",semana:2,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P7 – Turismo CDMX",formato:"Post estático",tipo:"MUNDIAL",tema:"El Mundial continúa y CDMX sigue siendo sede del mundo",copy:"El Mundial continúa. ⚽\nY CDMX sigue siendo la sede del mundo. 🎭\n\nMientras el planeta tiene los ojos puestos en esta ciudad,\nlos escenarios siguen abiertos cada noche.\n\nDos espectáculos. Una misma ciudad.\nLa combinación perfecta.\n\n¿Ya tienes tu plan de teatro para esta semana?\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #Mundial2026 #QueHacerEnCDMX #CDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s2_06",fecha:"Mié 8",dia:"Miércoles",mes:"Julio",semana:2,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"",tema:"Le dije a mi cartera no te preocupes porque en Teatrando hay descuentos",copy:"Le dije a mi cartera:\n'No te preocupes...' 😌💸\n\nPorque descubrí que en Teatrando\nhay boletos con descuento. 😎🎭\n\nTodos queremos ahorrar...\npero también queremos salir.\n\nLa buena noticia:\nNo tienes que elegir.\n\n¿Cuál fue el mejor descuento que encontraste?\n\n#Teatrando #TeatroCDMX #DescuentosTeatro #MemeTeatro #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s2_07",fecha:"Jue 9",dia:"Jueves",mes:"Julio",semana:2,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"",tema:"Cartelera fin de semana 10-12 julio",copy:"¿Ya tienes tu plan del fin? 🎭\n\n🧠 MÉTODO DE GRONHOLM · Vie-Dom · Teatro Xola\n😂 TRIPAS CORAZÓN · Sáb-Dom · Foro Coyoacanense — ÚLTIMAS FUNCIONES\n👑 LAS LEONAS · Sáb-Dom · Teatro México\n😂 ME DA PENA MI EX · Vie 8:45pm · Foro Lenin\n👻 Y LLEGARON LAS BRUJAS · Jue-Dom · Centro Roldán\n🎭 FANTASMA DE LA ÓPERA · Mar 8:30pm · Centro Roldán\n🎤 EL AMOR ES UNA MIERDA · Mar 8pm · La Teatrería\n🎭 DIÁLOGOS DE INFIDELIDADES · Dom 6pm · Foro Shakespeare\n🐱 CAPERUCITA ROCK'JA · Dom 11am y 1pm · Foro Shakespeare\n\nDesliza y elige.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PlanFinDeSemana #ObrasDeCDMX #CarteleraCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s2_08",fecha:"Jue 9",dia:"Jueves",mes:"Julio",semana:2,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"",tema:"Ya no eres del montón, ir al teatro es elegir experiencias que ningún algoritmo puede darte",copy:"YA NO ERES DEL MONTÓN. 🎭\n\nPorque mientras todos pasan horas haciendo scroll...\ntú decidiste vivir una historia real.\n\nIr al teatro es elegir experiencias\nque ningún algoritmo puede darte.\n\nEl teatro no compite contra Netflix.\nCompite contra la costumbre.\n\n¿Quién merece salir del algoritmo contigo?\nEtiquétalo. 👇\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #TeatroParaTodos #VivirElTeatro",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s2_09",fecha:"Vie 10",dia:"Viernes",mes:"Julio",semana:2,pub:1,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P1 – Curaduría",formato:"Reel",tipo:"",tema:"Conoce los teatros de CDMX",copy:"CDMX tiene más de 200 recintos teatrales activos. 🎭\n\nPero hay algunos que tienes que conocer sí o sí:\n\n🎭 Teatro Fernando Soler — la experiencia del Sótano\n🎭 Teatro Insurgentes — los grandes musicales\n🎭 Foro Shakespeare — el indie que te cambia\n🎭 Centro Roldán — suspenso y clásicos épicos\n🎭 Teatro Xola — lo que nadie más se atreve a hacer\n\nCada uno tiene su mundo.\n¿Cuál es el tuyo?\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #TeatrosDeCDMX #ObrasDeCDMX",estado:"Pendiente",notas:"Material propio",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s2_10",fecha:"Vie 10",dia:"Viernes",mes:"Julio",semana:2,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P2 – Planes",formato:"Post estático",tipo:"",tema:"Plan de viernes, arranca el fin de semana con teatro",copy:"Es viernes. 🎭\nY el telón ya está listo.\n\nEsta noche en CDMX:\n🧠 Método de Gronholm · 8pm · Teatro Xola\n😂 Sor-presas Amén · 8:30pm · Teatro Hidalgo\n🌹 Perfume de Gardenia · 9:15pm · Teatro San Rafael\n🎤 Risa & Tonic · 8:30 y 10:30pm · Foro Shakespeare\n🎭 Archivo Confidencial · 8pm · Teatro Varsovia\n😂 Stand Up Distrito Condesa · 8:30pm · Foro Shakespeare\n\n¿Ya elegiste?\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PlanViernes #ObrasDeCDMX #CarteleraCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s2_11",fecha:"Sáb 11",dia:"Sábado",mes:"Julio",semana:2,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"",tema:"Cartelera fin de semana 11-13 julio",copy:"¿Ya tienes tu plan este fin? 🎭\n\n👑 LAS LEONAS · Sáb 6 y 8:30pm · Dom 5 y 7pm · Teatro México\n😂 SOR-PRESAS AMÉN · Sáb 6 y 8:30pm · Dom 6pm · Teatro Hidalgo\n🎨 FRIDA KAHLO EL MUSICAL · Sáb 5 y 7:30pm · Dom 6pm · Teatro Centenario Coyoacán\n💔 DIVORCIÉMONOS MI AMOR · Sáb 5:40 y 8pm · Dom 4:40 y 7pm · Nuevo Broadway\n🎭 BUSCO AL HOMBRE DE MI VIDA · Sáb-Dom · Teatro San Jerónimo\n😂 SOLTERA PERO NO PARA CUALQUIERA · Dom 6pm · Foro Lenin\n🎭 MUCHO RUIDO POCAS NUECES · Dom 6pm · Teatro Varsovia\n🎵 RISA & TONIC · Sáb 8:30 y 10:30pm · Foro Shakespeare\n\nDesliza y elige.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PlanFinDeSemana #ObrasDeCDMX #CarteleraCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s2_12",fecha:"Sáb 11",dia:"Sábado",mes:"Julio",semana:2,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"RECOMENDACION",tema:"Afterglow cierra temporada el domingo 12, última oportunidad",copy:"⏰ ÚLTIMO FIN DE SEMANA\n\n🎵 AFTERGLOW\n\nEsta obra cierra temporada este domingo.\nSi la tenías en tu lista — hoy o mañana es el momento.\n\nTeatro que se atreve a ir donde pocos llegan.\nUna historia que no se olvida.\n\n📍 Teatro Milán\n🗓️ Sáb 6 y 8pm · Dom 12 — ÚLTIMA FUNCIÓN\n🎟️ teatrando.com.mx\n\n#Teatrando #Afterglow #TeatroCDMX #UltimaFuncion #ObrasDeCDMX",estado:"Pendiente",notas:"Afterglow termina el 12 julio",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s2_13",fecha:"Dom 12",dia:"Domingo",mes:"Julio",semana:2,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P7 – Turismo CDMX",formato:"Post estático",tipo:"MUNDIAL",tema:"El Mundial continúa, CDMX sigue siendo la sede del mundo",copy:"El Mundial continúa. ⚽🌎\nY CDMX sigue siendo la sede del mundo.\n\nMientras tanto — esta noche los escenarios siguen abiertos.\n\nPorque en esta ciudad el espectáculo no para.\nNi en la cancha ni bajo los reflectores.\n\n¿Ya tienes tu plan de teatro para cerrar el fin?\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #Mundial2026 #CDMX #QueHacerEnCDMX",estado:"Pendiente",notas:"Sin mencionar resultado de México",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s2_14",fecha:"Dom 12",dia:"Domingo",mes:"Julio",semana:2,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P4 – Servicio",formato:"Post estático",tipo:"",tema:"Danzite 2x1 todo el mes de julio, plan teatral al mejor precio",copy:"🎭 DANZITE 2x1 TODO JULIO\n\n¿Dos entradas al precio de una?\n\nSí. Durante todo julio el Espacio Teatral Danzite tiene 2x1:\n\n😱 Psicópata · Sáb 8:45pm · Dom 6:30pm\n🎭 El Asesino del Bosque · Sáb 7pm\n💃 Merlina y Pericles · Dom 5pm\n🔥 Siempre los Hombres las Prefieren Cabronas · Sáb 5:30pm\n\nEl mejor plan del mes — al mejor precio.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #Danzite #TeatroCDMX #2x1 #ObrasDeCDMX",estado:"Pendiente",notas:"Danzite 2x1 todo julio",disenho:"",cta:"teatrando.com.mx"},
// ── SEMANA 3: 13-19 julio ──
{id:"jul_s3_01",fecha:"Lun 13",dia:"Lunes",mes:"Julio",semana:3,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P1 – Curaduría",formato:"Carrusel",tipo:"RECOMENDACION",tema:"Ride the Cyclone 2da temporada, Divorciémonos mi Amor, Sor-presas Amén y Busco al Hombre de mi Vida",copy:"LA RECOMENDACIÓN TEATRANDO DE ESTA SEMANA 🎭\n\n🎵 RIDE THE CYCLONE — 2DA TEMPORADA\nEl musical más original de CDMX regresó. Y viene mejor.\n📍 Teatro Xola · Martes 8:30pm\n\n💔 DIVORCIÉMONOS MI AMOR\nComedia de pareja que duele de lo real que es.\n📍 Nuevo Broadway · Vie-Dom\n\n😂 SOR-PRESAS AMÉN\nSemanas en cartelera y el teatro sigue lleno. Por algo es.\n📍 Teatro Hidalgo · Vie-Dom\n\n🎭 BUSCO AL HOMBRE DE MI VIDA\nComedia que se ríe de lo que más nos importa.\n📍 Teatro San Jerónimo · Sáb-Dom\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #CarteleraCDMX #RecomendacionTeatrando",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s3_02",fecha:"Lun 13",dia:"Lunes",mes:"Julio",semana:3,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"FRASE",tema:"Frase de la semana",copy:"'La creatividad es la inteligencia divirtiéndose.' 🎭✨\n— Albert Einstein\n\nY nosotros nos tomamos muy en serio divertirnos.\nTe esperamos en el teatro.\n\n#Teatrando #FraseDeTeatro #TeatroCDMX #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s3_03",fecha:"Mar 14",dia:"Martes",mes:"Julio",semana:3,pub:1,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P1 – Curaduría",formato:"Reel",tipo:"",tema:"Lo que nadie te dice antes de ir al teatro por primera vez",copy:"Si vas al teatro por primera vez — escucha esto. 🎭\n\nPrimero: llega a tiempo. El teatro no espera a nadie.\n\nSegundo: apaga el celular. No para las fotos — para ti.\n\nTercero: no te preocupes si no entiendes todo.\nEl teatro habla de otra manera.\n\nCuarto: deja que te sorprenda.\nEso es exactamente para lo que está hecho.\n\nY quinto: cuando termines — quédate un momento.\nLo que sientes después también es parte de la obra.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PrimeraVezEnElTeatro #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s3_04",fecha:"Mar 14",dia:"Martes",mes:"Julio",semana:3,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P3 – Experiencia",formato:"Carrusel",tipo:"",tema:"Ninguna gran obra se sostiene con una sola emoción",copy:"Ninguna gran obra se sostiene con una sola emoción. 🎭✨\n\nEl teatro une...\n✨ risas\n✨ nostalgia\n✨ sorpresa\n✨ reflexión\n✨ esperanza\n\nY cuando todo eso se mezcla...\naparece la magia del escenario.\n\n¿Cuál emoción te hace volver una y otra vez al teatro?\nCuéntanos 👇\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #MagiaDelTeatro",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s3_05",fecha:"Mié 15",dia:"Miércoles",mes:"Julio",semana:3,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P7 – Turismo CDMX",formato:"Post estático",tipo:"MUNDIAL",tema:"El Mundial avanza y CDMX sigue siendo capital del mundo y del teatro",copy:"Avanza el torneo. ⚽\nY CDMX sigue siendo la capital del mundo y del teatro. 🎭\n\nEsta semana la ciudad tiene dos razones para vivirse completa:\n\n⚽ Los mejores partidos del planeta\n🎭 Más de 40 obras en cartelera cada noche\n\nNo elijas uno. Vive los dos.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #Mundial2026 #CDMX #QueHacerEnCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s3_06",fecha:"Mié 15",dia:"Miércoles",mes:"Julio",semana:3,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"",tema:"El que fue al teatro una vez vs el que nunca ha ido",copy:"El que nunca ha ido al teatro: 😐\n'No sé si es para mí...'\n\nEl que fue UNA VEZ: 😭🤯👏\n'¿Cuándo es la próxima función?'\n\nTodo el que ha vivido esto\nsabe exactamente de qué hablamos.\n\n¿A quién se lo mandas? 👇\n\n#Teatrando #TeatroCDMX #MemeTeatro #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s3_07",fecha:"Jue 16",dia:"Jueves",mes:"Julio",semana:3,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"VACACIONES",tema:"Cartelera fin de semana 17-19 julio, arranca vacaciones de verano",copy:"Arrancaron las vacaciones. 🌞🎭\nY la cartelera está mejor que nunca.\n\n😱 EL SÓTANO · Vie-Dom · Teatro Fernando Soler\n🌹 PERFUME DE GARDENIA · Sáb-Dom · Teatro San Rafael\n👑 LAS LEONAS · Sáb-Dom · Teatro México\n💔 DIVORCIÉMONOS MI AMOR · Vie-Dom · Nuevo Broadway\n🎵 NOTRE DAME DE PARÍS · Sáb 6 y 8:30pm — ÚLTIMA SEMANA\n😂 SOR-PRESAS AMÉN · Vie-Dom · Teatro Hidalgo\n🎭 ESQUIZOFRENIA · Mié-Jue 8:30pm · Teatro Enrique Lizalde\n🎨 FRIDA KAHLO EL MUSICAL · Sáb-Dom · Teatro Centenario Coyoacán\n\nDesliza y elige el tuyo.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #VacacionesDeVerano #PlanFinDeSemana #ObrasDeCDMX",estado:"Pendiente",notas:"Vacaciones inician el 16",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s3_08",fecha:"Jue 16",dia:"Jueves",mes:"Julio",semana:3,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P2 – Planes",formato:"Post estático",tipo:"VACACIONES",tema:"El mejor plan para las vacaciones de verano es el teatro, guía para toda la familia",copy:"Vacaciones de verano. 🌞\n¿Qué hacemos?\n\nLa respuesta más fácil, más barata y más memorable:\n\n🎭 EL TEATRO.\n\nCDMX tiene la cartelera perfecta para estas vacaciones:\nObras infantiles, comedias, musicales, suspenso, drama...\n\nAlgo para cada integrante de la familia.\n\n¿Ya tienes tu plan?\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #VacacionesDeVerano #PlanFamiliar #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s3_09",fecha:"Vie 17",dia:"Viernes",mes:"Julio",semana:3,pub:1,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P1 – Curaduría",formato:"Reel",tipo:"",tema:"Tres teatros de CDMX que tienes que conocer",copy:"3 teatros de CDMX que tienes que conocer este verano. 🎭\n\n🎭 FORO SHAKESPEARE\nEl corazón del teatro independiente en la ciudad.\nSiempre hay algo que te va a sorprender.\n\n🎭 CENTRO ROLDÁN SANDOVAL\nDonde el Fantasma de la Ópera convive con las Brujas.\nGrande, imponente y siempre lleno.\n\n🎭 ESPACIO TEATRAL DANZITE\nVariedad, precio accesible y 2x1 todo julio.\nUna joya que pocos conocen.\n\n¿Cuál falta en tu lista?\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #TeatrosMexicanos #ObrasDeCDMX #VacacionesDeVerano",estado:"Pendiente",notas:"Material propio",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s3_10",fecha:"Vie 17",dia:"Viernes",mes:"Julio",semana:3,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"",tema:"Notre Dame de París termina el 18, última oportunidad para verla",copy:"⏰ ÚLTIMA OPORTUNIDAD.\n\n🔔 NOTRE DAME DE PARÍS\n\nMañana sábado 18 es la última función.\nAmor, tragedia y la música que ya tienes en la cabeza.\n\nSi no la has visto — mañana es el día.\nNo esperes más.\n\n📍 Teatro Rafael Solana\n🗓️ Sáb 18 · 6 y 8:30pm\n🎟️ teatrando.com.mx\n\n#Teatrando #NotreDame #TeatroCDMX #UltimaFuncion #ObrasDeCDMX",estado:"Pendiente",notas:"Última función sábado 18 julio",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s3_11",fecha:"Sáb 18",dia:"Sábado",mes:"Julio",semana:3,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"VACACIONES",tema:"Cartelera fin de semana 18-20 julio, especial vacaciones de verano",copy:"Vacaciones de verano en CDMX. 🌞🎭\nLa cartelera no se toma descanso.\n\n🔔 NOTRE DAME DE PARÍS · Hoy última función · Teatro Rafael Solana\n😱 EL SÓTANO · Sáb-Dom · Teatro Fernando Soler\n🌹 PERFUME DE GARDENIA · Sáb-Dom · Teatro San Rafael\n👑 LAS LEONAS · Sáb-Dom · Teatro México\n🎨 FRIDA KAHLO EL MUSICAL · Sáb-Dom · Teatro Centenario Coyoacán\n💔 DIVORCIÉMONOS MI AMOR · Sáb-Dom · Nuevo Broadway\n🎭 VILLANOS DESPERADOS · Sáb 18 · ESTRENO\n🎤 RISA & TONIC · Sáb 8:30 y 10:30pm · Foro Shakespeare\n\nDesliza y elige.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #VacacionesDeVerano #PlanFinDeSemana #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s3_12",fecha:"Sáb 18",dia:"Sábado",mes:"Julio",semana:3,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"",tema:"Querido Teatro, carta de un espectador feliz",copy:"Querido Teatro... 🎭❤️\n\nGracias por recordarme\nque todavía puedo sorprenderme,\nreír sin mirar el celular,\nemocionarme con desconocidos\ny salir siendo una persona distinta.\n\nCon cariño,\nUn espectador feliz.\n\nTodos tenemos una obra que nos cambió.\n¿Cuál fue la tuya? Cuéntanos 👇\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #CartaAlTeatro",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s3_13",fecha:"Dom 19",dia:"Domingo",mes:"Julio",semana:3,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P7 – Turismo CDMX",formato:"Post estático",tipo:"MUNDIAL",tema:"CDMX vivió algo histórico, cierre del eje Mundial",copy:"CDMX vivió algo histórico. 🌎⚽🎭\n\nEsta ciudad fue sede del Mundial.\nEsta ciudad abrió su cartelera teatral al mundo.\nEsta ciudad demostró que no es solo una sede de fútbol —\nes una capital cultural de primer nivel.\n\nGracias por vivirlo con nosotros.\n\nEl telón sigue levantado. 🎭\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #Mundial2026 #CDMX #CierreDeTemporada",estado:"Pendiente",notas:"Último post del eje Mundial",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s3_14",fecha:"Dom 19",dia:"Domingo",mes:"Julio",semana:3,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P2 – Planes",formato:"Post estático",tipo:"VACACIONES",tema:"Plan familiar de domingo, obras para llevar a los niños este julio",copy:"Domingo de vacaciones. ¿Ya tienen plan? 🌞👨‍👩‍👧\n\nEsta semana en CDMX:\n\n🎵 DESCUBRIENDO A CRI CRI · Sáb-Dom 1pm · Teatro Hidalgo\n🐱 GATO CON BOTAS · Sáb 1:30pm · Teatro Wilberto Cantón\n🧚 PETER PAN · Dom 4pm · Centro Roldán\n🎭 BENITO TAMBIÉN PUEDE · Sáb 2pm · Talón de Asfalto\n🫎 AXOLOTL · Dom 1pm · Última función de hoy\n\nEl mejor recuerdo de vacaciones no es el que compras — es el que vives.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroInfantil #TeatroCDMX #VacacionesDeVerano #PlanFamiliar",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
// ── SEMANA 4: 20-26 julio ──
{id:"jul_s4_01",fecha:"Lun 20",dia:"Lunes",mes:"Julio",semana:4,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P1 – Curaduría",formato:"Carrusel",tipo:"RECOMENDACION",tema:"El Deseo de lo Prohibido, La Obscenidad de la Carne, Las Leonas y Conversando con el Diablo",copy:"LA RECOMENDACIÓN TEATRANDO DE ESTA SEMANA 🎭\n\n🔥 EL DESEO DE LO PROHIBIDO\nPasión, secretos y un escenario que no da respiro.\n📍 Teatro Renacimiento · Jue 8pm · Vie 6:40pm · Dom 7pm\n\n🖤 LA OBSCENIDAD DE LA CARNE\nTeatro que incomoda porque dice la verdad.\n📍 Teatro Renacimiento · Vie 6:40pm · Sáb 5:40 y 8pm · Dom 4:40pm\n\n👑 LAS LEONAS\nFuerza femenina en su forma más pura.\n📍 Teatro México · Sáb 6 y 8:30pm · Dom 5 y 7pm\n\n😈 CONVERSANDO CON EL DIABLO\nEl mal tiene muchas formas — esta es la más teatral.\n📍 Teatro Enrique Lizalde · Lun-Mar 8:30pm\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #CarteleraCDMX #RecomendacionTeatrando",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s4_02",fecha:"Lun 20",dia:"Lunes",mes:"Julio",semana:4,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"FRASE",tema:"Frase de la semana",copy:"'El teatro no puede desaparecer porque es el único arte donde la humanidad se enfrenta a sí misma.' 🎭✨\n— Arthur Miller\n\nY CDMX tiene el escenario listo para que lo vivas.\n\n#Teatrando #FraseDeTeatro #TeatroCDMX #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s4_03",fecha:"Mar 21",dia:"Martes",mes:"Julio",semana:4,pub:1,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P3 – Experiencia",formato:"Reel",tipo:"VACACIONES",tema:"Por qué ir al teatro en vacaciones de verano",copy:"Por qué el teatro es el mejor plan de vacaciones. 🌞🎭\n\nPrimero: es diferente a todo lo que ya conoces.\n\nSegundo: no hay pantallas de por medio.\nSolo historia, actores y tú.\n\nTercero: cada función es única.\nNo se repite. No se puede ver después.\n\nCuarto: sales con algo que no tenías al entrar.\nUna pregunta. Una emoción. Una perspectiva nueva.\n\nEso es lo que buscan las vacaciones, ¿no?\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #VacacionesDeVerano #ObrasDeCDMX",estado:"Pendiente",notas:"Material propio",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s4_04",fecha:"Mar 21",dia:"Martes",mes:"Julio",semana:4,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P4 – Servicio",formato:"Post estático",tipo:"",tema:"Danzite 2x1 julio, segunda llamada para aprovechar el descuento",copy:"Segunda llamada. 🎭\n\n🎟️ DANZITE 2x1 TODO JULIO\n\nSi aún no has ido — quedan pocos fines de semana.\n\n😱 Psicópata · Sáb 8:45pm · Dom 6:30pm\n🎭 El Asesino del Bosque · Sáb 7pm\n💃 Merlina y Pericles · Dom 5pm\n🔥 ¿Qué no me Caché mi Marido? · Vie 8:30pm\n\nDos entradas. Un precio.\nEl mejor plan de vacaciones al alcance de todos.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #Danzite #TeatroCDMX #2x1 #VacacionesDeVerano",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s4_05",fecha:"Mié 22",dia:"Miércoles",mes:"Julio",semana:4,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"VACACIONES",tema:"Obras infantiles y familiares en cartelera julio, plan para toda la familia",copy:"Las mejores obras infantiles de julio. 🌞👨‍👩‍👧🎭\n\n🎵 DESCUBRIENDO A CRI CRI\nLas canciones que te saben a infancia.\n📍 Teatro Hidalgo · Sáb-Dom 1pm\n\n🐱 GATO CON BOTAS\nAventura, magia y humor en cada función.\n📍 Teatro Wilberto Cantón · Sáb 1:30pm\n\n🧚 PETER PAN\nEl clásico que nunca envejece.\n📍 Centro Roldán Sandoval · Dom 4pm\n\n🎭 BENITO TAMBIÉN PUEDE\nUna historia de valentía para los más chicos.\n📍 Talón de Asfalto · Sáb 2pm\n\n🎶 TRIBUTO A LAS K POP\nMúsica y show para toda la familia.\n📍 Foro Coapa · Sáb-Dom 2:30pm\n\nDesliza y elige el plan de este fin.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroInfantil #TeatroCDMX #VacacionesDeVerano #PlanFamiliar",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s4_06",fecha:"Mié 22",dia:"Miércoles",mes:"Julio",semana:4,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P5 – Prueba social",formato:"Post estático",tipo:"",tema:"Confiesa, ¿cuál es el peor comportamiento que has visto en un teatro?",copy:"CONFIESA. 🎭\n\n¿Cuál es el peor comportamiento\nque has visto en un teatro?\n\n📱 Alguien usando el celular toda la obra\n😴 Alguien dormido en primera fila\n🗣️ Alguien hablando sin parar\n🤣 Alguien riéndose donde nadie más reía\n\nTodos tenemos una anécdota.\nCuéntanosla 👇\n\n#Teatrando #TeatroCDMX #ConfesoesDeTeatro #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s4_07",fecha:"Jue 23",dia:"Jueves",mes:"Julio",semana:4,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"",tema:"Cartelera fin de semana 24-26 julio",copy:"¿Ya tienes tu plan del fin? 🎭\n\n😱 EL SÓTANO · Vie-Dom · Teatro Fernando Soler\n🌹 PERFUME DE GARDENIA · Sáb-Dom · Teatro San Rafael\n👑 LAS LEONAS · Sáb-Dom · Teatro México\n🖤 LA OBSCENIDAD DE LA CARNE · Vie-Dom · Teatro Renacimiento\n🎭 RETRATO SEÑOR MOLIÈRE · Vie 24 8pm · Teatro Varsovia — FUNCIÓN ÚNICA\n😈 INFIERNO · Vie 8:30pm · Sáb 6 y 8:30pm · Teatro Enrique Lizalde\n🎤 RISA & TONIC · Vie-Sáb · Foro Shakespeare\n🎭 COMO QUIERAS PERO ÁMAME · Jue-Vie 8:30pm · Virginia Fábregas\n🎭 TOCÓ TRES VECES PERO NO ABRÍ · Vie 24 8:30pm · Foro Sylvia Pasquel\n\nDesliza y elige.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PlanFinDeSemana #ObrasDeCDMX #CarteleraCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s4_08",fecha:"Jue 23",dia:"Jueves",mes:"Julio",semana:4,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P2 – Planes",formato:"Post estático",tipo:"VACACIONES",tema:"El teatro como plan de pareja, obras románticas y de comedia para salir esta semana",copy:"El plan de pareja perfecto para estas vacaciones. 💑🎭\n\nNo es una cena más.\nNo es otra serie en streaming.\n\nEs compartir algo que no se puede pausar,\nque solo existe en ese momento.\n\nEsta semana las opciones ideales:\n🌹 Perfume de Gardenia — romanticismo puro\n💔 Divorciémonos mi Amor — comedia que une más de lo que separa\n😈 El Que se Enamora Pierde — cuando el corazón no calcula\n\n¿Ya le propusiste el plan?\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PlanDePareja #VacacionesDeVerano #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s4_09",fecha:"Vie 24",dia:"Viernes",mes:"Julio",semana:4,pub:1,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P3 – Experiencia",formato:"Reel",tipo:"",tema:"Así se vive una noche de teatro en CDMX",copy:"Así se vive una noche de teatro en CDMX. 🌆🎭\n\nEmpieza eligiendo tu obra en teatrando.com.mx\nLlegas al teatro cinco minutos antes\nApagas el celular\nEl telón sube\n\nY durante las próximas dos horas\nel mundo exterior deja de existir.\n\nSolo la historia.\nSolo los actores.\nSolo tú.\n\nAl final — un aplauso que vale todo.\n\nEso es lo que te estás perdiendo si no has ido.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #NocheDeTeatro #ObrasDeCDMX #VacacionesDeVerano",estado:"Pendiente",notas:"Material propio",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s4_10",fecha:"Vie 24",dia:"Viernes",mes:"Julio",semana:4,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"RECOMENDACION",tema:"Retrato Señor Molière, tres funciones únicas en Teatro Varsovia",copy:"Para el público que busca algo diferente. 🎭\n\n🎩 RETRATO SEÑOR MOLIÈRE\n\nTres funciones únicas en Teatro Varsovia.\nTeatro de texto. De oficio. De los que no se repiten.\n\nSi eres de los que disfrutan una obra\nque les exige algo a cambio — esta es para ti.\n\n📍 Teatro Varsovia\n🗓️ Jue 23 · Vie 24 8pm · Sáb 25 7pm\n🎟️ teatrando.com.mx\n\n#Teatrando #RetratoDeMoliere #TeatroCDMX #TeatroDeTexto #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s4_11",fecha:"Sáb 25",dia:"Sábado",mes:"Julio",semana:4,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"",tema:"Cartelera fin de semana 25-27 julio",copy:"¿Ya tienes tu plan este fin? 🎭\n\n😱 EL SÓTANO · Sáb-Dom · Teatro Fernando Soler\n🌹 PERFUME DE GARDENIA · Sáb-Dom · Teatro San Rafael\n🎩 RETRATO SR. MOLIÈRE · Sáb 25 7pm · Teatro Varsovia — ÚLTIMA FUNCIÓN\n😂 SOR-PRESAS AMÉN · Sáb-Dom · Teatro Hidalgo\n🔥 INFIERNO · Sáb 6 y 8:30pm · Teatro Enrique Lizalde\n🎭 JUEGO QUE TODOS JUGAMOS · Jue-Sáb 8:30pm · Dom 7:30pm · Teatro Wilberto Cantón\n🌍 RECORRIDO LEYENDAS XOCHIMILCO · Sáb 27 5:30pm · Embarcadero Caltongo\n🎤 RISA & TONIC · Sáb 8:30 y 10:30pm · Foro Shakespeare\n\nDesliza y elige.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PlanFinDeSemana #ObrasDeCDMX #CarteleraCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s4_12",fecha:"Sáb 25",dia:"Sábado",mes:"Julio",semana:4,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"ESTRENO",tema:"Villanos Desperados, estreno de temporada",copy:"🚨 ESTRENO DE TEMPORADA\n\n😈 VILLANOS DESPERADOS\n\nEl lado oscuro también merece su momento en el escenario.\nY hoy es el día.\n\nConsigue tus boletos en teatrando.com.mx\nantes de que se agoten.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #VillanosDesperados #TeatroCDMX #Estreno #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s4_13",fecha:"Dom 26",dia:"Domingo",mes:"Julio",semana:4,pub:1,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"VACACIONES",tema:"El domingo perfecto en familia, obras infantiles y planes para hoy",copy:"Domingo de vacaciones. ¿Ya tienen plan? 🌞👨‍👩‍👧🎭\n\nHOY EN CDMX:\n\n🎵 DESCUBRIENDO A CRI CRI · 1pm · Teatro Hidalgo\n🧚 PETER PAN · 4pm · Centro Roldán Sandoval\n🎭 BENITO TAMBIÉN PUEDE · 2pm · Talón de Asfalto\n👑 IMPERIO · 7pm · Castillo Chapultepec\n😂 HUEVOS DE MI MADRE · 5pm · Teatro Silvia Pinal\n\nAlgo para cada integrante de la familia.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PlanFamiliar #VacacionesDeVerano #TeatroInfantil",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s4_14",fecha:"Dom 26",dia:"Domingo",mes:"Julio",semana:4,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P5 – Prueba social",formato:"Post estático",tipo:"",tema:"¿Qué tipo de espectador eres en vacaciones de verano?",copy:"🌞 Edición vacaciones de verano:\n\n¿Qué tipo de espectador eres?\n\n🏖️ El que busca teatro en la ciudad que visita\n🏠 El que se queda en CDMX y aprovecha la cartelera\n😴 El que tenía plan de ir pero al final no fue\n🎭 El que ya tiene su obra de julio comprada\n\n¿Cuál eres tú?\nCuéntanos en los comentarios 👇\n\n#Teatrando #TeatroCDMX #VacacionesDeVerano #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
// ── SEMANA 5: 27-31 julio ──
{id:"jul_s5_01",fecha:"Lun 27",dia:"Lunes",mes:"Julio",semana:5,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P1 – Curaduría",formato:"Carrusel",tipo:"RECOMENDACION",tema:"El Sótano, Divorciémonos mi Amor, Sobreviviendo a Cyrano y Psicópata",copy:"LA RECOMENDACIÓN TEATRANDO DE ESTA SEMANA 🎭\n\n😱 EL SÓTANO\nLa experiencia que no se puede spoilear — solo vivir.\n📍 Teatro Fernando Soler · Vie 7 y 9:15pm · Sáb 6 y 8:30pm · Dom 5 y 7:30pm\n\n💔 DIVORCIÉMONOS MI AMOR\nComedia de pareja que duele de lo real que es.\n📍 Nuevo Broadway · Vie-Dom\n\n🎩 SOBREVIVIENDO A CYRANO\nAmor, ingenio y una historia que no termina como esperas.\n📍 Teatro Varsovia · Jueves 8pm\n\n😱 PSICÓPATA\nTerror psicológico que te hace cuestionar todo lo que ves.\n📍 Espacio Teatral Danzite · Sáb 8:45pm · Dom 6:30pm\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #CarteleraCDMX #RecomendacionTeatrando",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s5_02",fecha:"Lun 27",dia:"Lunes",mes:"Julio",semana:5,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"FRASE",tema:"Frase de la semana",copy:"'La vida es una obra de teatro que no permite ensayos. Canta, ríe, baila, llora y vive intensamente cada momento, antes de que el telón baje.' 🎭✨\n— Charles Chaplin\n\nJulio casi termina. Que no te quede ninguna función pendiente.\n\n#Teatrando #FraseDeTeatro #TeatroCDMX #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s5_03",fecha:"Mar 28",dia:"Martes",mes:"Julio",semana:5,pub:1,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P3 – Experiencia",formato:"Reel",tipo:"VACACIONES",tema:"El mejor plan de verano que nadie te había contado",copy:"El mejor plan de vacaciones que nadie te había contado. 🌞🎭\n\nNo es un resort.\nNo es un parque de diversiones.\nNo es otra serie en streaming.\n\nEs una obra de teatro en CDMX.\n\nDos horas que no se parecen a nada más.\nUna historia que te lleva a otro lugar.\nUn aplauso que vale todo el verano.\n\nY con descuentos exclusivos en Teatrando —\nel mejor plan resulta ser también el más accesible.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #VacacionesDeVerano #ObrasDeCDMX",estado:"Pendiente",notas:"Material propio",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s5_04",fecha:"Mar 28",dia:"Martes",mes:"Julio",semana:5,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P4 – Servicio",formato:"Post estático",tipo:"",tema:"Danzite 2x1 últimos días de julio, aprovecha antes de que termine",copy:"Últimos días. ⏰🎭\n\n🎟️ DANZITE 2x1 — CIERRA ESTE MES\n\nEl 2x1 en el Espacio Teatral Danzite termina con julio.\nSi aún no has ido — esta es tu última oportunidad.\n\n😱 Psicópata · Sáb 8:45pm · Dom 6:30pm\n🎭 El Asesino del Bosque · Sáb 7pm\n💃 Merlina y Pericles · Dom 5pm\n\nDos entradas al precio de una.\nNo lo dejes para agosto.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #Danzite #TeatroCDMX #2x1 #UltimosDias",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s5_05",fecha:"Mié 29",dia:"Miércoles",mes:"Julio",semana:5,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P2 – Planes",formato:"Post estático",tipo:"VACACIONES",tema:"Última semana de julio, ¿ya viste tu obra del mes?",copy:"Última semana de julio. ⏰🎭\n\n¿Ya viste tu obra del mes?\n\nSi la respuesta es no —\nesta semana es tu oportunidad.\n\nLa cartelera sigue completa:\n😱 El Sótano\n🌹 Perfume de Gardenia\n🎨 Frida Kahlo el Musical\n🖤 La Obscenidad de la Carne\n💔 Divorciémonos mi Amor\n😂 Sor-presas Amén\n\nNo dejes que julio se vaya sin teatro.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #VacacionesDeVerano #ObrasDeCDMX #UltimaSemanadeJulio",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s5_06",fecha:"Mié 29",dia:"Miércoles",mes:"Julio",semana:5,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"",tema:"Polirrítmicas y un Extravío, función única para el público que busca algo diferente",copy:"Para el público que busca algo distinto. 🎭\n\n🎶 POLIRRÍTMICAS Y UN EXTRAVÍO\n\nUna propuesta que cruza música, cuerpo y teatro\nen una función que no se va a repetir.\n\nSi eres de los que quieren ver teatro que arriesga —\nesta noche en Teatro Varsovia es para ti.\n\n📍 Teatro Varsovia\n🗓️ Miércoles 29 julio · 8pm\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #TeatroExperimental #ObrasDeCDMX #FuncionUnica",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s5_07",fecha:"Jue 30",dia:"Jueves",mes:"Julio",semana:5,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"",tema:"Cartelera fin de semana 31 julio al 2 agosto",copy:"El último fin de julio y el primero de agosto. 🎭\n\n😱 EL SÓTANO · Vie-Dom · Teatro Fernando Soler\n🌹 PERFUME DE GARDENIA · Vie-Dom · Teatro San Rafael\n👑 LAS LEONAS · Sáb-Dom · Teatro México\n🖤 LA OBSCENIDAD DE LA CARNE · Vie-Dom · Teatro Renacimiento\n😂 SOR-PRESAS AMÉN · Vie-Dom · Teatro Hidalgo\n🎤 RISA & TONIC · Vie-Sáb · Foro Shakespeare\n🎭 TOCÓ TRES VECES PERO NO ABRÍ · Vie 31 8:30pm · Foro Sylvia Pasquel\n💃 VELOCIDAD DEL OTOÑO · Sáb 6pm · Teatro Silvia Pinal\n😂 HUEVOS DE MI MADRE · Dom 5pm · Teatro Silvia Pinal\n\nDesliza y elige el tuyo.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PlanFinDeSemana #ObrasDeCDMX #CarteleraCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s5_08",fecha:"Jue 30",dia:"Jueves",mes:"Julio",semana:5,pub:2,redes:["Instagram Feed","Facebook"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"FRASE",tema:"Frase de cierre de julio",copy:"'¡Mi reino por un caballo!' dijo Ricardo III.\n\nNosotros decimos: 🎭✨\n¡Tu butaca por una función que no olvidarás!\n\n— William Shakespeare, Ricardo III\n\nJulio cerró el telón con el corazón lleno.\nGracias por elegirnos. Agosto viene con más. 🙌\n\n#Teatrando #TeatroCDMX #FraseDeTeatro #CierreDeJulio #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"jul_s5_09",fecha:"Vie 31",dia:"Viernes",mes:"Julio",semana:5,pub:1,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P1 – Curaduría",formato:"Reel",tipo:"",tema:"Así fue julio en el teatro de CDMX, resumen del mes",copy:"Así fue julio en el teatro de CDMX. 🎭\n\nFue el mes del Mundial y los escenarios abiertos.\nFue el mes de las vacaciones de verano.\nFue el mes de las últimas funciones y los primeros estrenos.\n\nFue el mes que demostró que CDMX no duerme.\nNi en la cancha ni bajo los reflectores.\n\nGracias por ser parte de esto.\n\nAgosto viene con todo. 🎭\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #ResumenJulio #ObrasDeCDMX",estado:"Pendiente",notas:"Material propio",disenho:"",cta:"teatrando.com.mx"},
{id:"jul_s5_10",fecha:"Vie 31",dia:"Viernes",mes:"Julio",semana:5,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P2 – Planes",formato:"Post estático",tipo:"",tema:"Cierre de julio y adelanto de agosto",copy:"Julio cerró el telón. 🎭\n\nFue el mes del Mundial y el teatro.\nDe las vacaciones y el escenario.\nDe las últimas funciones que valió la pena ver.\n\nAgosto llega con más:\n🎭 El Sótano continúa\n🎭 Las Leonas siguen en cartelera\n🎭 Nuevos estrenos confirmados\n🎭 Ride the Cyclone — 2da temporada\n\nSíguenos para la cartelera completa de agosto.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #CierreJulio #AdelantoAgosto #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
];

const buildResenasJulio = () => [
{id:"rj_01",semana:1,obra:"El Sótano",titulo:"La experiencia que no te puedes perder, sin spoilers"},
{id:"rj_02",semana:1,obra:"Método de Gronholm",titulo:"Suspenso corporativo que no te suelta desde la primera escena"},
{id:"rj_03",semana:1,obra:"Axolotl La Aventura del Cacao Perdido",titulo:"La aventura infantil más divertida de la cartelera de julio"},
{id:"rj_04",semana:1,obra:"Archivo Confidencial",titulo:"El thriller que lleva el suspenso al siguiente nivel"},
{id:"rj_05",semana:1,obra:"Las 5 obras que tienes que ver en CDMX si vienes al Mundial",titulo:"Guía teatral para el visitante del torneo"},
{id:"rj_06",semana:2,obra:"Afterglow",titulo:"La obra que cierra temporada y no puedes perderte"},
{id:"rj_07",semana:2,obra:"Ride the Cyclone el Musical 2da temporada",titulo:"El musical más original de CDMX regresó mejor que nunca"},
{id:"rj_08",semana:2,obra:"Hoy No Me Puedo Levantar",titulo:"El musical que te pone de pie aunque no quieras"},
{id:"rj_09",semana:2,obra:"Notre Dame de París",titulo:"Amor y tragedia con música que no se olvida, últimas funciones"},
{id:"rj_10",semana:2,obra:"Guía de teatro para el viajero del Mundial",titulo:"Todo lo que no sabías que podías vivir en CDMX más allá del partido"},
{id:"rj_11",semana:3,obra:"La Obscenidad de la Carne",titulo:"Teatro que incomoda porque dice la verdad"},
{id:"rj_12",semana:3,obra:"El Deseo de lo Prohibido",titulo:"Pasión, secretos y un escenario que no da respiro"},
{id:"rj_13",semana:3,obra:"Descubriendo a Cri Cri",titulo:"El plan familiar perfecto para este verano"},
{id:"rj_14",semana:3,obra:"Todo el Mundo Habla de Jamie",titulo:"La historia que demuestra que el escenario siempre ha sido un espacio seguro"},
{id:"rj_15",semana:3,obra:"Teatro en vacaciones de verano, guía completa para familias CDMX julio 2026",titulo:"El mejor plan que no sabías que existía"},
{id:"rj_16",semana:4,obra:"Perfume de Gardenia",titulo:"Glamour, nostalgia y una voz que no se olvida"},
{id:"rj_17",semana:4,obra:"Carry",titulo:"El estreno que llega para quedarse en la cartelera de CDMX"},
{id:"rj_18",semana:4,obra:"Matilda el Musical 2da temporada",titulo:"La magia regresa — y viene mejor que antes"},
{id:"rj_19",semana:4,obra:"Recorrido de Leyendas de Xochimilco Colonial",titulo:"La experiencia nocturna más única de CDMX este verano"},
{id:"rj_20",semana:4,obra:"Por qué el verano es la mejor temporada para descubrir el teatro independiente en CDMX",titulo:"Teatro independiente que tienes que conocer este julio"},
];

const BRIEFING_JULIO = `📌 LÍNEA EDITORIAL JULIO 2026

S1 (1-5 jul): Publicados 1-3 + fin de semana partido México
S2 (6-12 jul): Mundial continúa + presentación cartelera julio
S3 (13-19 jul): Mundial cierre (hasta el 19) + arranque Vacaciones de Verano
S4 (20-26 jul): Vacaciones de Verano + estrenos
S5 (27-31 jul): Vacaciones de Verano + cierre de mes y adelanto agosto`;
const POLL_INTERVAL = 4000;

async function saveData(data) {
  try {
    const res = await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:JSON.stringify(data)})});
    return res.ok;
  } catch(e) { return false; }
}
async function loadData() {
  try {
    const res = await fetch('/api/data');
    const json = await res.json();
    if (json.data) return JSON.parse(json.data);
  } catch(e) {}
  return null;
}
async function callClaude(prompt,maxTokens=1200) {
  const r = await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-6",max_tokens:maxTokens,messages:[{role:"user",content:prompt}]})});
  const d = await r.json();
  return d.content?.[0]?.text||"";
}
async function generarCopyIA(item) {
  const prompt = `Eres el community manager de Teatrando CDMX. Voz: cercana, entusiasta, confiable.\nGenera copy para redes sociales:\n- Pilar: ${item.pilar}\n- Tema: ${item.tema}\n- Formato: ${item.formato}\n- Redes: ${(item.redes||[]).join(", ")}\nREGLAS: Hook potente primera línea, beneficio antes que info, frases cortas, emojis relevantes, máximo 6 líneas, urgencia suave al cierre, 5 hashtags incluyendo #Teatrando.\nDevuelve SOLO el copy listo para publicar.`;
  return await callClaude(prompt);
}

export default function App() {
  const isMounted = useRef(true);
  const modoClienteRef = useRef(true);
  const saveTimerRef = useRef(null);
  const [parrillas,setParrillas] = useState({"Julio":buildJulio()});
  const [resenas,setResenas] = useState({"Julio":buildResenasJulio()});
  const [briefings,setBriefings] = useState({"Julio":BRIEFING_JULIO});
  const [semanaActiva,setSemanaActiva] = useState(1);
  const [cardAbierta,setCardAbierta] = useState(null);
  const [filtros,setFiltros] = useState({pilar:"Todos",formato:"Todos"});
  const [vista,setVista] = useState("parrilla");
  const [vistaCliente,setVistaCliente] = useState("parrilla");
  const [notifMsg,setNotifMsg] = useState("");
  const [generando,setGenerando] = useState({});
  const [syncStatus,setSyncStatus] = useState("idle");
  const [lastRefresh,setLastRefresh] = useState("");
  const [modoCliente,setModoCliente] = useState(true);
  const [showAdminLogin,setShowAdminLogin] = useState(false);
  const [passInput,setPassInput] = useState("");
  const [passError,setPassError] = useState(false);
  const [modalAgregarDia,setModalAgregarDia] = useState(false);
  const [nuevoDiaForm,setNuevoDiaForm] = useState({fecha:"",dia:"Lunes",semana:1,numPubs:2,tipo:""});
  const [editandoBriefing,setEditandoBriefing] = useState(false);
  const [marcandoId,setMarcandoId] = useState(null);
  const [editandoFechaId,setEditandoFechaId] = useState(null);
  const [nuevaFecha,setNuevaFecha] = useState("");

  const mesActivo = "Julio";
  const parrilla = parrillas[mesActivo]||[];
  const resenasMes = resenas[mesActivo]||[];
  const briefingMes = briefings[mesActivo]||"";
  const semanasDelMes = [...new Set(parrilla.map(p=>p.semana))].sort((a,b)=>a-b);
  const notif = (msg) => { setNotifMsg(msg); setTimeout(()=>setNotifMsg(""),2800); };
  const doLogin = () => { if(passInput===ADMIN_PASS){setModoCliente(false);modoClienteRef.current=false;setShowAdminLogin(false);setPassInput("");setPassError(false);}else setPassError(true); };
  const doLogout = () => { setModoCliente(true); modoClienteRef.current=true; };

  useEffect(()=>{
    isMounted.current=true;
    (async()=>{ const saved=await loadData(); if(saved&&isMounted.current){if(saved.parrillas)setParrillas(saved.parrillas);if(saved.resenas)setResenas(saved.resenas);if(saved.briefings)setBriefings(saved.briefings);} })();
    return ()=>{ isMounted.current=false; };
  },[]);

  const guardarAdmin = useCallback(async(data)=>{
    if(modoClienteRef.current) return;
    if(saveTimerRef.current) clearTimeout(saveTimerRef.current);
    setSyncStatus("saving");
    saveTimerRef.current = setTimeout(async()=>{ const ok=await saveData(data); if(isMounted.current){setSyncStatus(ok?"saved":"error");setTimeout(()=>{if(isMounted.current)setSyncStatus("idle");},2000);} },800);
  },[]);

  useEffect(()=>{
    const interval=setInterval(async()=>{ if(!modoClienteRef.current) return; const saved=await loadData(); if(saved&&isMounted.current){if(saved.parrillas)setParrillas(saved.parrillas);if(saved.resenas)setResenas(saved.resenas);if(saved.briefings)setBriefings(saved.briefings);setLastRefresh(new Date().toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit",second:"2-digit"}));} },POLL_INTERVAL);
    return ()=>clearInterval(interval);
  },[]);

  const sortP = (arr) => [...arr].sort((a,b)=>{ if(a.semana!==b.semana)return a.semana-b.semana; const nA=parseInt((a.fecha||"").replace(/\D/g,"")||"0"),nB=parseInt((b.fecha||"").replace(/\D/g,"")||"0"); if(nA!==nB)return nA-nB; return(a.pub||0)-(b.pub||0); });

  const editarCampo = useCallback((id,campo,valor)=>{
    if(modoClienteRef.current) return;
    setParrillas(prev=>{ const item=(prev[mesActivo]||[]).find(p=>p.id===id);if(!item)return prev; regCambio(id,campo,item[campo],valor); let nl=prev[mesActivo].map(p=>p.id===id?{...p,[campo]:valor}:p); if(campo==="fecha")nl=sortP(nl); const nuevo={...prev,[mesActivo]:nl}; guardarAdmin({parrillas:nuevo,resenas,briefings,mesesDisp:["Julio"]}); return nuevo; });
  },[mesActivo,resenas,briefings,guardarAdmin]);

  const editarCampoCliente = async(id,campo,valor)=>{
    setMarcandoId(id);
    try {
      const saved=await loadData();
      if(saved&&saved.parrillas&&saved.parrillas[mesActivo]){
        saved.parrillas[mesActivo]=saved.parrillas[mesActivo].map(p=>p.id===id?{...p,[campo]:valor}:p);
        const ok=await saveData(saved);
        if(ok&&isMounted.current) setParrillas(prev=>({...prev,[mesActivo]:(prev[mesActivo]||[]).map(p=>p.id===id?{...p,[campo]:valor}:p)}));
      } else {
        setParrillas(prev=>{ const nuevo={...prev,[mesActivo]:(prev[mesActivo]||[]).map(p=>p.id===id?{...p,[campo]:valor}:p)}; saveData({parrillas:nuevo,resenas,briefings,mesesDisp:["Julio"]}); return nuevo; });
      }
    } catch(e){}
    setMarcandoId(null);
  };

  const toggleRed = useCallback((id,red)=>{ if(modoClienteRef.current)return; setParrillas(prev=>{ const item=(prev[mesActivo]||[]).find(p=>p.id===id);if(!item)return prev; const nv=item.redes.includes(red)?item.redes.filter(r=>r!==red):[...item.redes,red]; const nuevo={...prev,[mesActivo]:prev[mesActivo].map(p=>p.id===id?{...p,redes:nv}:p)}; guardarAdmin({parrillas:nuevo,resenas,briefings,mesesDisp:["Julio"]}); return nuevo; }); },[mesActivo,resenas,briefings,guardarAdmin]);

  const editarResena = useCallback((id,campo,valor)=>{ if(modoClienteRef.current)return; setResenas(prev=>{ const nuevo={...prev,[mesActivo]:prev[mesActivo].map(r=>r.id===id?{...r,[campo]:valor}:r)}; guardarAdmin({parrillas,resenas:nuevo,briefings,mesesDisp:["Julio"]}); return nuevo; }); },[mesActivo,parrillas,briefings,guardarAdmin]);

  const handleGenerarCopy = async(item)=>{ setGenerando(prev=>({...prev,[item.id]:true})); try{const nc=await generarCopyIA(item);editarCampo(item.id,"copy",nc);notif("✨ Copy actualizado");}catch(e){notif("⚠ Error al generar copy");} setGenerando(prev=>({...prev,[item.id]:false})); };
  const handleEliminarPub = (id)=>{ if(modoClienteRef.current)return; setParrillas(prev=>{ const nuevo={...prev,[mesActivo]:prev[mesActivo].filter(p=>p.id!==id)}; guardarAdmin({parrillas:nuevo,resenas,briefings,mesesDisp:["Julio"]}); return nuevo; }); setCardAbierta(null); notif("🗑 Publicación eliminada"); };
  const handleAgregarResena = ()=>{ if(modoClienteRef.current)return; const nr=buildResena({semana:semanaActiva,obra:"Nueva obra"}); setResenas(prev=>{ const nuevo={...prev,[mesActivo]:[...(prev[mesActivo]||[]),nr]}; guardarAdmin({parrillas,resenas:nuevo,briefings,mesesDisp:["Julio"]}); return nuevo; }); notif("✅ Reseña agregada"); };
  const handleEliminarResena = (id)=>{ if(modoClienteRef.current)return; setResenas(prev=>{ const nuevo={...prev,[mesActivo]:prev[mesActivo].filter(r=>r.id!==id)}; guardarAdmin({parrillas,resenas:nuevo,briefings,mesesDisp:["Julio"]}); return nuevo; }); notif("🗑 Reseña eliminada"); };
  const handleAgregarDia = ()=>{ if(!nuevoDiaForm.fecha){notif("⚠ Escribe una fecha");return;} const pubs=[]; for(let i=1;i<=nuevoDiaForm.numPubs;i++)pubs.push(buildPub({fecha:nuevoDiaForm.fecha,dia:nuevoDiaForm.dia,semana:parseInt(nuevoDiaForm.semana),pub:i,tipo:nuevoDiaForm.tipo||""})); setParrillas(prev=>{ const nuevo={...prev,[mesActivo]:sortP([...(prev[mesActivo]||[]),...pubs])}; guardarAdmin({parrillas:nuevo,resenas,briefings,mesesDisp:["Julio"]}); return nuevo; }); setModalAgregarDia(false);setNuevoDiaForm({fecha:"",dia:"Lunes",semana:1,numPubs:2,tipo:""});notif(`✅ "${nuevoDiaForm.fecha}" agregado`); };
  const marcarSemana = (estado)=>{ if(modoClienteRef.current)return; setParrillas(prev=>{ const nuevo={...prev,[mesActivo]:prev[mesActivo].map(p=>p.semana===semanaActiva?{...p,estado}:p)}; guardarAdmin({parrillas:nuevo,resenas,briefings,mesesDisp:["Julio"]}); return nuevo; }); notif(`Semana ${semanaActiva} → ${estado}`); };

  const filtradas=parrilla.filter(p=>{ if(p.semana!==semanaActiva)return false; if(filtros.pilar!=="Todos"&&p.pilar!==filtros.pilar)return false; if(filtros.formato!=="Todos"&&!p.formato.toLowerCase().includes(filtros.formato.toLowerCase().replace(" estático","").replace(" interactiva","")))return false; return true; });
  const byDate={};filtradas.forEach(p=>{if(!byDate[p.fecha])byDate[p.fecha]=[];byDate[p.fecha].push(p);});
  const byDateCliente={};(parrillas[mesActivo]||[]).filter(p=>p.semana===semanaActiva).forEach(p=>{if(!byDateCliente[p.fecha])byDateCliente[p.fecha]=[];byDateCliente[p.fecha].push(p);});
  const mix=useMemo(()=>{ const t=parrilla.length||1; return{p123:Math.round(parrilla.filter(p=>["P1 – Curaduría","P2 – Planes","P3 – Experiencia"].includes(p.pilar)).length/t*100),p4:Math.round(parrilla.filter(p=>p.pilar==="P4 – Servicio").length/t*100),p56:Math.round(parrilla.filter(p=>["P5 – Prueba social","P6 – Cultura"].includes(p.pilar)).length/t*100)}; },[parrilla]);
  const sc=e=>ESTADO_CFG[e]||ESTADO_CFG["Pendiente"];
  const IS={width:"100%",background:"#0a0a0a",color:"#fff",border:"1px solid #1e1e1e",borderRadius:6,padding:"6px 9px",fontSize:11,boxSizing:"border-box",fontFamily:"inherit"};
  const BTN=({active,onClick,children,style={},danger=false,small=false,disabled=false})=>(<button onClick={onClick} disabled={disabled} style={{padding:small?"4px 10px":"6px 16px",borderRadius:20,border:danger?"1.5px solid #7f1d1d":(active?"2px solid #C40803":"1.5px solid #252525"),background:danger?"#2d0000":(active?"#C40803":"#111"),color:danger?"#ff6b6b":"#fff",fontWeight:700,cursor:disabled?"not-allowed":"pointer",fontSize:small?10:11,opacity:disabled?0.5:1,transition:"all 0.15s",...style}}>{children}</button>);
  const etiq=s=>s===1?"1-5 jul":s===2?"6-12 jul":s===3?"13-19 jul":s===4?"20-26 jul":"27-31 jul";

  if(showAdminLogin) return(
    <div style={{fontFamily:"Segoe UI,system-ui,sans-serif",background:"#0a0a0a",minHeight:"100vh",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center"}}>
      <div style={{background:"#111",border:"1px solid #C40803",borderRadius:16,padding:36,width:340,maxWidth:"90vw",textAlign:"center"}}>
        <div style={{fontSize:32,marginBottom:6}}>🎭</div>
        <div style={{fontSize:9,color:"rgba(255,255,255,0.4)",letterSpacing:3,textTransform:"uppercase",marginBottom:4}}>Área de Administración</div>
        <div style={{fontSize:24,fontWeight:900,color:"#C40803",marginBottom:20}}>TEATRANDO</div>
        <input type="password" value={passInput} onChange={e=>{setPassInput(e.target.value);setPassError(false);}} onKeyDown={e=>{if(e.key==="Enter")doLogin();}} placeholder="Contraseña..." autoFocus style={{...IS,marginBottom:8,textAlign:"center",fontSize:14,letterSpacing:4}}/>
        {passError&&<div style={{fontSize:10,color:"#C40803",marginBottom:8}}>Contraseña incorrecta.</div>}
        <div style={{display:"flex",gap:8,justifyContent:"center",marginTop:8}}><BTN onClick={doLogin}>Entrar</BTN><BTN onClick={()=>{setShowAdminLogin(false);setPassInput("");setPassError(false);}} danger small>Cancelar</BTN></div>
      </div>
    </div>
  );

  if(modoCliente) return(
    <div style={{fontFamily:"Segoe UI,system-ui,sans-serif",background:"#0a0a0a",minHeight:"100vh",color:"#fff"}}>
      <div style={{background:"linear-gradient(135deg,#C40803 0%,#8B0000 60%,#0a0a0a 100%)",padding:"16px 20px",borderBottom:"2px solid #C40803"}}>
        <div style={{maxWidth:900,margin:"0 auto"}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:10,marginBottom:12}}>
            <div style={{display:"flex",alignItems:"center",gap:12}}>
              <div style={{fontSize:26,fontWeight:900,color:"#fff",letterSpacing:-1}}>🎭 Teatrando</div>
              <div><div style={{fontSize:8,color:"rgba(255,255,255,0.6)",letterSpacing:3,textTransform:"uppercase"}}>Propuesta de Contenido</div><div style={{fontSize:20,fontWeight:900}}>JULIO 2026</div></div>
            </div>
            <BTN onClick={()=>setShowAdminLogin(true)} small style={{background:"rgba(0,0,0,0.3)",border:"1px solid rgba(255,255,255,0.2)"}}>🔐 Admin</BTN>
          </div>
          <div style={{display:"flex",alignItems:"center",gap:6,marginBottom:10}}>
            <span style={{width:7,height:7,borderRadius:"50%",background:"#22c55e",display:"inline-block"}}/>
            <span style={{fontSize:8,color:"rgba(255,255,255,0.5)",letterSpacing:1}}>EN VIVO · refresca cada 4s</span>
            {lastRefresh&&<span style={{fontSize:8,color:"rgba(255,255,255,0.3)"}}>· {lastRefresh}</span>}
          </div>
          <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>
            <BTN active={vistaCliente==="parrilla"} onClick={()=>setVistaCliente("parrilla")} small>📋 Parrilla</BTN>
            <BTN active={vistaCliente==="resenas"} onClick={()=>setVistaCliente("resenas")} small>📖 Reseñas</BTN>
            <BTN active={vistaCliente==="bitacora"} onClick={()=>setVistaCliente("bitacora")} small>📒 Bitácora</BTN>
          </div>
        </div>
      </div>
      <div style={{maxWidth:900,margin:"0 auto",padding:"16px 14px"}}>
        <div style={{marginBottom:14,display:"flex",gap:6,flexWrap:"wrap"}}>
          {semanasDelMes.map(s=>(<button key={s} onClick={()=>setSemanaActiva(s)} style={{padding:"5px 14px",borderRadius:18,border:semanaActiva===s?"2px solid #C40803":"1.5px solid #222",background:semanaActiva===s?"#C40803":"#111",color:"#fff",fontWeight:700,cursor:"pointer",fontSize:10}}>S{s} <span style={{opacity:0.7}}>({etiq(s)})</span></button>))}
        </div>
        {briefingMes&&<div style={{background:"#111",border:"1px solid #C40803",borderRadius:10,padding:"12px 16px",marginBottom:16}}><div style={{fontSize:9,color:"#C40803",fontWeight:700,letterSpacing:2,textTransform:"uppercase",marginBottom:6}}>📋 Línea editorial Julio</div><pre style={{fontSize:11,color:"#ccc",lineHeight:1.7,whiteSpace:"pre-wrap",fontFamily:"inherit",margin:0}}>{briefingMes}</pre></div>}
        {vistaCliente==="parrilla"&&(<>
          <div style={{fontSize:10,color:"#444",marginBottom:12}}>
            {(parrillas[mesActivo]||[]).filter(p=>p.semana===semanaActiva).length} publicaciones · <span style={{color:"#22c55e"}}>{(parrillas[mesActivo]||[]).filter(p=>p.semana===semanaActiva&&p.estado==="Publicado").length} publicadas</span> · <span style={{color:"#3b82f6"}}>{(parrillas[mesActivo]||[]).filter(p=>p.semana===semanaActiva&&p.estado==="En producción").length} en producción</span>
          </div>
          {Object.entries(byDateCliente).map(([fecha,pubs])=>(
            <div key={fecha} style={{marginBottom:16}}>
              <div style={{fontSize:10,color:"#C40803",fontWeight:700,marginBottom:8,display:"flex",alignItems:"center",gap:8}}><span style={{background:"#C40803",color:"#fff",padding:"2px 12px",borderRadius:5}}>{fecha}</span><div style={{flex:1,height:1,background:"#1a1a1a"}}/></div>
              {pubs.map(p=>{
                const ec=sc(p.estado);const marcando=marcandoId===p.id;
                return(<div key={p.id} style={{background:"#0d0d0d",border:p.disenho==="para_disenar"?"2px solid #C40803":p.disenho==="disenho_realizado"?"2px solid #059669":"1px solid #161616",borderLeft:`3px solid ${PILAR_COLOR[p.pilar]||"#333"}`,borderRadius:8,padding:"12px 14px",marginBottom:8}}>
                  {p.disenho==="para_disenar"&&(<div style={{background:"#C40803",color:"#fff",fontSize:9,fontWeight:900,padding:"4px 12px",borderRadius:4,marginBottom:8,display:"flex",alignItems:"center",justifyContent:"space-between",letterSpacing:1}}><span>🎨 Para diseñar</span><button onClick={()=>{if(!marcando)editarCampoCliente(p.id,"disenho","disenho_realizado");}} disabled={marcando} style={{background:"#fff",color:"#C40803",border:"none",borderRadius:4,padding:"2px 10px",fontSize:8,fontWeight:900,cursor:marcando?"not-allowed":"pointer",opacity:marcando?0.6:1}}>{marcando?"Guardando...":"Marcar como realizado"}</button></div>)}
                  {p.disenho==="disenho_realizado"&&(<div style={{background:"#059669",color:"#fff",fontSize:9,fontWeight:900,padding:"4px 12px",borderRadius:4,marginBottom:8,letterSpacing:1}}>✅ Diseño realizado</div>)}
                  <div style={{display:"flex",gap:5,marginBottom:6,flexWrap:"wrap",alignItems:"center"}}>
                    {p.tipo&&<span style={{fontSize:8,background:TIPO_COLOR[p.tipo]||"#555",color:"#fff",padding:"2px 8px",borderRadius:4,fontWeight:900,textTransform:"uppercase"}}>{p.tipo}</span>}
                    <span style={{fontSize:8,color:"#fff",background:PILAR_COLOR[p.pilar]||"#333",padding:"2px 8px",borderRadius:6,fontWeight:700}}>{p.pilar}</span>
                    <span style={{fontSize:8,color:"#666"}}>{p.formato}</span>
                    <span style={{marginLeft:"auto",fontSize:10,color:ec.color,background:ec.bg,padding:"3px 12px",borderRadius:20,border:`1.5px solid ${ec.color}`,fontWeight:900}}>{p.estado}</span>
                  </div>
                  <div style={{fontSize:14,fontWeight:700,color:"#fff",marginBottom:8}}>{p.tema}</div>
                  {p.copy&&<pre style={{fontSize:11,color:"#bbb",lineHeight:1.7,whiteSpace:"pre-wrap",fontFamily:"inherit",margin:"0 0 10px"}}>{p.copy}</pre>}
                  <div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{(p.redes||[]).map(r=><span key={r} style={{fontSize:9,color:RED_COLOR[r]||"#aaa",background:"#1a1a1a",padding:"2px 7px",borderRadius:6}}>{RED_ICON[r]} {r}</span>)}</div>
                  {p.notas&&p.notas!=="YA PUBLICADO"&&<div style={{fontSize:9,color:"#444",marginTop:6,fontStyle:"italic"}}>📌 {p.notas}</div>}
                </div>);
              })}
            </div>
          ))}
        </>)}
        {vistaCliente==="resenas"&&(<div>
          <div style={{fontSize:11,color:"#555",marginBottom:16}}>{resenasMes.length} reseñas planificadas para Julio</div>
          {[1,2,3,4].map(s=>{ const rs=resenasMes.filter(r=>r.semana===s);if(!rs.length)return null;
            return(<div key={s} style={{marginBottom:28}}>
              <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><span style={{fontSize:9,color:"#fff",background:"#C40803",fontWeight:700,textTransform:"uppercase",letterSpacing:2,padding:"3px 12px",borderRadius:6}}>Semana {s}</span><div style={{flex:1,height:1,background:"#1a1a1a"}}/></div>
              {rs.map(r=>(<div key={r.id} style={{background:"#0d0d0d",border:"1px solid #1a1a1a",borderRadius:10,padding:"12px 14px",marginBottom:8}}><div style={{fontSize:13,fontWeight:700,color:"#fff",marginBottom:4}}>{r.obra||"Sin título"}</div>{r.titulo&&<div style={{fontSize:10,color:"#C40803",fontStyle:"italic"}}>{r.titulo}</div>}</div>))}
            </div>);
          })}
        </div>)}
        {vistaCliente==="bitacora"&&(<div>
          {(()=>{
            const pubsMes=parrillas[mesActivo]||[];
            const semanasMes=[...new Set(pubsMes.map(p=>p.semana))].sort((a,b)=>a-b);
            const conMov=pubsMes.some(p=>p.estado==="Publicado"||p.estado==="En producción");
            if(!conMov)return<div style={{textAlign:"center",padding:40,color:"#333",fontSize:12,border:"1px dashed #1a1a1a",borderRadius:10}}>📒 Aún no hay publicaciones registradas.</div>;
            return semanasMes.map(s=>{ const ps=pubsMes.filter(p=>p.semana===s);const pub=ps.filter(p=>p.estado==="Publicado");const prod=ps.filter(p=>p.estado==="En producción");if(!pub.length&&!prod.length)return null;
              return(<div key={s} style={{marginBottom:28}}>
                <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><div style={{background:"#C40803",color:"#fff",fontWeight:900,fontSize:10,padding:"4px 14px",borderRadius:6,textTransform:"uppercase"}}>Semana {s} · {etiq(s)}</div><div style={{flex:1,height:1,background:"#1a1a1a"}}/></div>
                {pub.length>0&&<div style={{marginBottom:10}}><div style={{fontSize:8,color:"#22c55e",fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:8,paddingLeft:4}}>✅ Publicado</div><div style={{borderLeft:"2px solid #22c55e40",paddingLeft:12,display:"flex",flexDirection:"column",gap:6}}>{pub.map(p=><div key={p.id} style={{display:"flex",alignItems:"baseline",gap:10}}><span style={{fontSize:9,color:"#555",flexShrink:0,minWidth:44}}>{p.fecha}</span><span style={{fontSize:12,color:"#ddd",fontWeight:500}}>{p.tema}</span></div>)}</div></div>}
                {prod.length>0&&<div><div style={{fontSize:8,color:"#3b82f6",fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:8,paddingLeft:4}}>🔵 En producción</div><div style={{borderLeft:"2px solid #3b82f640",paddingLeft:12,display:"flex",flexDirection:"column",gap:6}}>{prod.map(p=><div key={p.id} style={{display:"flex",alignItems:"baseline",gap:10}}><span style={{fontSize:9,color:"#555",flexShrink:0,minWidth:44}}>{p.fecha}</span><span style={{fontSize:12,color:"#888",fontWeight:500}}>{p.tema}</span></div>)}</div></div>}
              </div>);
            });
          })()}
        </div>)}
        <div style={{textAlign:"center",marginTop:40,fontSize:9,color:"#1a1a1a",paddingBottom:20}}>Teatrando CDMX · @teatrandocdmx · teatrando.com.mx</div>
      </div>
    </div>
  );

  return(
    <div style={{fontFamily:"Segoe UI,system-ui,sans-serif",background:"#060606",minHeight:"100vh",color:"#fff",paddingBottom:60}}>
      {notifMsg&&<div style={{position:"fixed",top:16,right:16,background:"#C40803",color:"#fff",padding:"8px 18px",borderRadius:20,fontSize:11,fontWeight:700,zIndex:9999,boxShadow:"0 4px 16px rgba(196,8,3,0.5)"}}>{notifMsg}</div>}
      {modalAgregarDia&&(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.88)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1000}}>
        <div style={{background:"#111",border:"1px solid #C40803",borderRadius:12,padding:24,width:360,maxWidth:"90vw"}}>
          <div style={{fontSize:14,fontWeight:700,marginBottom:14}}>➕ Agregar publicación — Julio</div>
          {[{l:"Fecha (ej: Mié 25)",k:"fecha",t:"text"},{l:"Día de la semana",k:"dia",t:"select",ops:DIAS_SEMANA},{l:"Semana #",k:"semana",t:"number"},{l:"# publicaciones",k:"numPubs",t:"number"}].map(f=>(<div key={f.k} style={{marginBottom:10}}><div style={{fontSize:9,color:"#555",textTransform:"uppercase",letterSpacing:1,marginBottom:3,fontWeight:700}}>{f.l}</div>{f.t==="select"?<select value={nuevoDiaForm[f.k]} onChange={e=>setNuevoDiaForm(p=>({...p,[f.k]:e.target.value}))} style={{...IS}}>{f.ops.map(o=><option key={o} style={{background:"#111"}}>{o}</option>)}</select>:<input type={f.t} value={nuevoDiaForm[f.k]} onChange={e=>setNuevoDiaForm(p=>({...p,[f.k]:e.target.value}))} style={IS}/>}</div>))}
          <div style={{display:"flex",gap:8,marginTop:14}}><BTN onClick={handleAgregarDia}>✅ Agregar</BTN><BTN onClick={()=>setModalAgregarDia(false)} danger>Cancelar</BTN></div>
        </div>
      </div>)}
      <div style={{background:"linear-gradient(135deg,#C40803 0%,#7f0000 50%,#0a0a0a 100%)",padding:"18px 20px 14px",borderBottom:"2px solid #C40803"}}>
        <div style={{maxWidth:980,margin:"0 auto"}}>
          <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:10}}>
            <div style={{display:"flex",alignItems:"center",gap:12}}><div style={{fontSize:26,fontWeight:900,color:"#fff",letterSpacing:-1}}>🎭 Teatrando</div><div><div style={{fontSize:8,color:"rgba(255,255,255,0.6)",letterSpacing:3,textTransform:"uppercase"}}>Sistema de Contenido · Admin</div><div style={{fontSize:20,fontWeight:900}}>JULIO 2026</div></div></div>
            <div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}>
              {[{l:"Eng/Plan/Exp",v:mix.p123,t:70},{l:"Servicio",v:mix.p4,t:20},{l:"Cult/Social",v:mix.p56,t:10}].map(m=>(<div key={m.l} style={{background:"rgba(0,0,0,0.35)",borderRadius:7,padding:"3px 9px",border:`1px solid ${Math.abs(m.v-m.t)<=5?"#22c55e":"#C40803"}40`}}><div style={{fontSize:7,color:"rgba(255,255,255,0.5)"}}>{m.l}</div><div style={{fontSize:12,fontWeight:900,color:Math.abs(m.v-m.t)<=5?"#22c55e":"#f59e0b"}}>{m.v}%<span style={{fontSize:7,opacity:0.5,marginLeft:2}}>/{m.t}%</span></div></div>))}
              <BTN onClick={doLogout} small style={{background:"rgba(0,0,0,0.4)",border:"1px solid rgba(255,255,255,0.2)"}}>👁 Vista cliente</BTN>
              <div style={{fontSize:8,display:"flex",alignItems:"center",gap:4,padding:"3px 8px",borderRadius:10,background:"rgba(0,0,0,0.3)",border:`1px solid ${syncStatus==="saved"?"#22c55e":syncStatus==="saving"?"#f59e0b":syncStatus==="error"?"#ef4444":"#222"}`}}><span style={{width:6,height:6,borderRadius:"50%",background:syncStatus==="saved"?"#22c55e":syncStatus==="saving"?"#f59e0b":syncStatus==="error"?"#ef4444":"#333",display:"inline-block"}}/><span style={{color:syncStatus==="saved"?"#22c55e":syncStatus==="saving"?"#f59e0b":syncStatus==="error"?"#ef4444":"#555"}}>{syncStatus==="saving"?"Guardando...":syncStatus==="saved"?"✓ Guardado":syncStatus==="error"?"⚠ Error":"En línea"}</span></div>
            </div>
          </div>
          <div style={{display:"flex",gap:5,marginTop:12,flexWrap:"wrap"}}><BTN active={vista==="parrilla"} onClick={()=>setVista("parrilla")} small>📋 Parrilla</BTN><BTN active={vista==="resenas"} onClick={()=>setVista("resenas")} small>📝 Reseñas</BTN></div>
        </div>
      </div>
      <div style={{maxWidth:980,margin:"0 auto",padding:"0 14px"}}>
        <div style={{marginTop:12,marginBottom:10,display:"flex",gap:6,flexWrap:"wrap",alignItems:"center"}}>
          {semanasDelMes.map(s=>(<button key={s} onClick={()=>{setSemanaActiva(s);setCardAbierta(null);}} style={{padding:"5px 14px",borderRadius:18,border:semanaActiva===s?"2px solid #C40803":"1.5px solid #222",background:semanaActiva===s?"#C40803":"#111",color:"#fff",fontWeight:700,cursor:"pointer",fontSize:10}}>S{s} <span style={{fontSize:9,opacity:0.6}}>({etiq(s)}) ({parrilla.filter(p=>p.semana===s).length})</span></button>))}
        </div>
        <div style={{background:"#0a0a12",border:"1px solid #1a1a3a",borderRadius:10,padding:"10px 14px",marginBottom:12}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><div style={{fontSize:9,color:"#4455aa",textTransform:"uppercase",letterSpacing:1,fontWeight:700}}>📋 Línea editorial Julio 2026</div><button onClick={()=>setEditandoBriefing(!editandoBriefing)} style={{fontSize:9,color:"#4455aa",background:"transparent",border:"1px solid #1a1a3a",borderRadius:6,padding:"2px 8px",cursor:"pointer"}}>{editandoBriefing?"✅ Listo":"✏ Editar"}</button></div>
          {editandoBriefing?<textarea value={briefingMes} onChange={e=>{setBriefings(prev=>{const n={...prev,[mesActivo]:e.target.value};guardarAdmin({parrillas,resenas,briefings:n,mesesDisp:["Julio"]});return n;});}} rows={5} style={{width:"100%",background:"#060610",color:"#aaaadd",border:"1px solid #1a1a3a",borderRadius:7,padding:"8px 10px",fontSize:10,lineHeight:1.7,resize:"vertical",boxSizing:"border-box",fontFamily:"inherit"}}/>:<pre style={{fontSize:10,color:"#8888aa",lineHeight:1.7,whiteSpace:"pre-wrap",fontFamily:"inherit",margin:0}}>{briefingMes}</pre>}
        </div>
        {vista==="parrilla"&&(<>
          <div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center",marginBottom:10}}>
            {[{l:"Pilar",ops:["Todos",...PILARES],v:filtros.pilar,k:"pilar"},{l:"Formato",ops:["Todos","Post","Carrusel","Reel","Story"],v:filtros.formato,k:"formato"}].map(f=>(<div key={f.k} style={{display:"flex",gap:3,alignItems:"center",flexWrap:"wrap"}}><span style={{fontSize:8,color:"#333",textTransform:"uppercase",letterSpacing:1,fontWeight:700}}>{f.l}:</span>{f.ops.slice(0,6).map(o=>(<button key={o} onClick={()=>setFiltros(prev=>({...prev,[f.k]:o}))} style={{padding:"2px 7px",borderRadius:10,fontSize:8,border:f.v===o?"1.5px solid #C40803":"1px solid #1a1a1a",background:f.v===o?"#C40803":"#111",color:"#fff",cursor:"pointer",fontWeight:600}}>{o.replace("P1 – ","P1·").replace("P2 – ","P2·").replace("P3 – ","P3·").replace("P4 – ","P4·").replace("P5 – ","P5·").replace("P6 – ","P6·").replace(" estático","").replace(" interactiva","")}</button>))}</div>))}
            <button onClick={()=>setModalAgregarDia(true)} style={{marginLeft:"auto",padding:"4px 12px",borderRadius:16,border:"1.5px dashed #333",background:"transparent",color:"#666",cursor:"pointer",fontSize:10,fontWeight:700}}>+ Agregar día</button>
          </div>
          <div style={{fontSize:9,color:"#333",marginBottom:8,display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}>
            <span><span style={{color:"#C40803",fontWeight:700}}>{filtradas.length}</span> pubs · S{semanaActiva} ({etiq(semanaActiva)})</span>
            <div style={{marginLeft:"auto",display:"flex",gap:6}}>{["Publicado","En producción","Pendiente"].map(e=>(<button key={e} onClick={()=>marcarSemana(e)} style={{padding:"3px 10px",borderRadius:12,border:`1.5px solid ${sc(e).color}50`,background:"#0a0a0a",color:sc(e).color,cursor:"pointer",fontSize:9,fontWeight:700}}>{e==="Publicado"?"✅":e==="En producción"?"🔵":"⬜"} {e}</button>))}</div>
          </div>
          {Object.entries(byDate).map(([fecha,pubs])=>(
            <div key={fecha} style={{marginBottom:14}}>
              <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}><div style={{background:"#C40803",color:"#fff",fontWeight:900,fontSize:9,padding:"2px 9px",borderRadius:5}}>{fecha}</div><div style={{flex:1,height:1,background:"#141414"}}/></div>
              {pubs.map(p=>{ const isOpen=cardAbierta===p.id;const ec=sc(p.estado);
                return(<div key={p.id} style={{background:p.disenho==="para_disenar"?"#120000":p.disenho==="disenho_realizado"?"#001a0a":"#0b0b0b",border:isOpen?`1.5px solid ${PILAR_COLOR[p.pilar]||"#333"}`:(p.disenho==="para_disenar"?"1.5px solid #C4080350":p.disenho==="disenho_realizado"?"1.5px solid #05966950":"1px solid #141414"),borderRadius:9,marginBottom:5,overflow:"hidden"}}>
                  <div onClick={()=>setCardAbierta(isOpen?null:p.id)} style={{padding:"8px 11px",cursor:"pointer",display:"flex",alignItems:"center",gap:6,flexWrap:"wrap"}}>
                    <div style={{width:18,height:18,borderRadius:"50%",background:PILAR_COLOR[p.pilar]||"#333",display:"flex",alignItems:"center",justifyContent:"center",fontSize:8,fontWeight:900,flexShrink:0,color:"#fff"}}>{p.pub}</div>
                    {p.tipo&&<span style={{fontSize:8,background:TIPO_COLOR[p.tipo]||"#555",color:"#fff",padding:"2px 8px",borderRadius:4,fontWeight:900,textTransform:"uppercase"}}>{p.tipo}</span>}
                    <span style={{fontSize:7,background:PILAR_COLOR[p.pilar],color:"#fff",padding:"1px 5px",borderRadius:6,fontWeight:700}}>{p.pilar.split("–")[0].trim()}</span>
                    <span style={{fontSize:11,fontWeight:700,color:"#fff",flex:1,minWidth:100}}>{p.tema}</span>
                    {p.disenho==="para_disenar"&&<span style={{fontSize:8,color:"#C40803"}}>🎨</span>}
                    {p.disenho==="disenho_realizado"&&<span style={{fontSize:8,color:"#059669"}}>✅</span>}
                    <span style={{fontSize:7,background:ec.bg,color:ec.color,padding:"1px 5px",borderRadius:6,fontWeight:700,border:`1px solid ${ec.color}30`}}>{p.estado}</span>
                    <span style={{fontSize:9,color:isOpen?"#C40803":"#222"}}>{isOpen?"▲":"▼"}</span>
                  </div>
                  {isOpen&&(<div style={{padding:"0 11px 11px",borderTop:"1px solid #141414"}}>
                    <div style={{marginTop:9,display:"flex",alignItems:"center",gap:8}}>
                      <div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,fontWeight:700,minWidth:40}}>📅 Fecha</div>
                      {editandoFechaId===p.id?(<div style={{display:"flex",gap:6,flex:1}}><input value={nuevaFecha} onChange={e=>setNuevaFecha(e.target.value)} placeholder="ej: Mié 25" style={{...IS,width:"auto",flex:1}}/><button onClick={()=>{editarCampo(p.id,"fecha",nuevaFecha);setEditandoFechaId(null);notif("📅 Fecha actualizada — pub reordenada");}} style={{padding:"3px 10px",borderRadius:8,background:"#C40803",color:"#fff",border:"none",cursor:"pointer",fontSize:9,fontWeight:700}}>✓</button><button onClick={()=>setEditandoFechaId(null)} style={{padding:"3px 8px",borderRadius:8,background:"#222",color:"#aaa",border:"none",cursor:"pointer",fontSize:9}}>✕</button></div>):(<div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:11,color:"#fff",fontWeight:700}}>{p.fecha}</span><button onClick={()=>{setEditandoFechaId(p.id);setNuevaFecha(p.fecha);}} style={{padding:"2px 8px",borderRadius:6,background:"#1a1a1a",color:"#666",border:"1px solid #222",cursor:"pointer",fontSize:8}}>✏ Cambiar</button></div>)}
                    </div>
                    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:7,marginTop:9}}>
                      {[{l:"Pilar",campo:"pilar",ops:PILARES},{l:"Formato",campo:"formato",ops:FORMATOS},{l:"Estado",campo:"estado",ops:ESTADOS}].map(f=>(<div key={f.campo}><div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,marginBottom:2,fontWeight:700}}>{f.l}</div><select value={p[f.campo]||""} onChange={e=>editarCampo(p.id,f.campo,e.target.value)} style={{...IS,background:f.campo==="estado"?ec.bg:"#0d0d0d",color:f.campo==="estado"?ec.color:"#fff",border:`1px solid ${f.campo==="estado"?ec.color+"40":"#1a1a1a"}`}}>{f.ops.map(o=><option key={o} style={{background:"#111",color:"#fff"}}>{o}</option>)}</select></div>))}
                    </div>
                    <div style={{marginTop:10,display:"flex",alignItems:"center",gap:10}}>
                      <div style={{fontSize:9,fontWeight:700,color:"#555",textTransform:"uppercase",letterSpacing:1}}>Para diseñar:</div>
                      <button onClick={()=>{const next=p.disenho===""?"para_disenar":p.disenho==="para_disenar"?"disenho_realizado":"";editarCampo(p.id,"disenho",next);}} style={{padding:"4px 16px",borderRadius:20,fontWeight:900,fontSize:10,cursor:"pointer",background:p.disenho==="para_disenar"?"#C40803":p.disenho==="disenho_realizado"?"#059669":"#0a0a0a",color:p.disenho?"#fff":"#444",border:p.disenho==="para_disenar"?"2px solid #C40803":p.disenho==="disenho_realizado"?"2px solid #059669":"1.5px solid #333",transition:"all 0.2s"}}>{p.disenho==="para_disenar"?"🎨 Para diseñar":p.disenho==="disenho_realizado"?"✅ Diseño realizado":"Enviar a diseñar"}</button>
                    </div>
                    <div style={{marginTop:9}}><div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,marginBottom:3,fontWeight:700}}>Redes sociales</div><div style={{display:"flex",gap:3,flexWrap:"wrap"}}>{REDES.map(r=><button key={r} onClick={()=>toggleRed(p.id,r)} style={{padding:"2px 7px",borderRadius:8,fontSize:8,cursor:"pointer",fontWeight:600,background:(p.redes||[]).includes(r)?RED_COLOR[r]+"22":"#111",border:(p.redes||[]).includes(r)?`1.5px solid ${RED_COLOR[r]}`:"1px solid #222",color:(p.redes||[]).includes(r)?RED_COLOR[r]:"#555"}}>{RED_ICON[r]} {r}</button>)}</div></div>
                    <div style={{marginTop:9}}><div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,marginBottom:2,fontWeight:700}}>Tema</div><input value={p.tema||""} onChange={e=>editarCampo(p.id,"tema",e.target.value)} style={IS}/></div>
                    <div style={{marginTop:9}}>
                      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:3}}><div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,fontWeight:700}}>📝 Copy</div><button onClick={()=>handleGenerarCopy(p)} disabled={generando[p.id]} style={{background:generando[p.id]?"#1a1a1a":"#1a0000",color:generando[p.id]?"#444":"#C40803",border:`1px solid ${generando[p.id]?"#222":"#C40803"}`,borderRadius:12,padding:"2px 9px",fontSize:8,fontWeight:700,cursor:generando[p.id]?"not-allowed":"pointer"}}>{generando[p.id]?"⏳ Generando...":"✨ Generar con IA"}</button></div>
                      <textarea value={p.copy||""} onChange={e=>editarCampo(p.id,"copy",e.target.value)} rows={5} style={{...IS,background:"#060606",lineHeight:1.65,resize:"vertical"}}/>
                    </div>
                    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:7,marginTop:9}}>
                      {[{l:"🎯 CTA",k:"cta"},{l:"🎨 Link diseño",k:"linkDiseno",ph:"https://drive.google.com/..."},{l:"🗒 Notas",k:"notas",ph:"Pendiente..."}].map(f=>(<div key={f.k}><div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,marginBottom:2,fontWeight:700}}>{f.l}</div><input value={p[f.k]||""} placeholder={f.ph||""} onChange={e=>editarCampo(p.id,f.k,e.target.value)} style={{...IS,background:f.k==="notas"?"#060606":"#0a0a0a",border:f.k==="notas"?"1px dashed #1a1a1a":"1px solid #1e1e1e",color:f.k==="notas"?"#666":"#fff"}}/></div>))}
                    </div>
                    <div style={{marginTop:10,display:"flex",justifyContent:"flex-end"}}><button onClick={()=>handleEliminarPub(p.id)} style={{fontSize:9,color:"#7f1d1d",background:"transparent",border:"none",cursor:"pointer"}}>🗑 Eliminar</button></div>
                  </div>)}
                </div>);
              })}
            </div>
          ))}
        </>)}
        {vista==="resenas"&&(<div style={{marginTop:12}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}>
            <div><div style={{fontSize:12,fontWeight:700}}>Reseñas — Julio 2026</div><div style={{fontSize:9,color:"#444",marginTop:2}}>{resenasMes.length} reseñas · 5 por semana (semanas 1-4)</div></div>
            <button onClick={handleAgregarResena} style={{padding:"4px 12px",borderRadius:14,border:"1px solid #22c55e",background:"#002a10",color:"#22c55e",cursor:"pointer",fontSize:9,fontWeight:700}}>+ Nueva reseña</button>
          </div>
          {[1,2,3,4].map(s=>{ const rs=resenasMes.filter(r=>r.semana===s);
            return(<div key={s} style={{marginBottom:20}}>
              <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><span style={{fontSize:8,color:"#C40803",fontWeight:700,textTransform:"uppercase",letterSpacing:2}}>Semana {s}</span><div style={{flex:1,height:1,background:"#141414"}}/><span style={{fontSize:8,color:"#333"}}>{rs.length}/5</span></div>
              {rs.map(r=>(<div key={r.id} style={{background:"#0b0b0b",border:"1px solid #1a1a1a",borderRadius:9,padding:"9px 12px",marginBottom:6}}>
                <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:8}}>
                  <div style={{flex:1}}><input value={r.obra||""} onChange={e=>editarResena(r.id,"obra",e.target.value)} placeholder="Nombre de la obra o editorial" style={{width:"100%",background:"#111",border:"1px solid #222",borderRadius:5,padding:"3px 7px",color:"#fff",fontSize:11,marginBottom:4,fontWeight:700}}/><input value={r.titulo||""} onChange={e=>editarResena(r.id,"titulo",e.target.value)} placeholder="Título / ángulo SEO" style={{width:"100%",background:"#111",border:"1px solid #222",borderRadius:5,padding:"3px 7px",color:"#C40803",fontSize:10}}/></div>
                  <button onClick={()=>handleEliminarResena(r.id)} style={{background:"transparent",border:"none",color:"#555",cursor:"pointer",fontSize:14,padding:"2px 4px"}}>✕</button>
                </div>
              </div>))}
              {!rs.length&&<div style={{border:"1px dashed #1a1a1a",borderRadius:8,padding:"10px",textAlign:"center",color:"#333",fontSize:10}}>Sin reseñas.</div>}
            </div>);
          })}
        </div>)}
        <div style={{textAlign:"center",marginTop:28,fontSize:8,color:"#141414"}}>Teatrando CDMX · Sistema de Contenido 2026 · @teatrandocdmx</div>
      </div>
    </div>
  );
}
