import { useState, useEffect, useRef, useMemo, useCallback } from "react";

const REDES = ["Instagram Feed","Instagram Stories","Instagram Reels","Facebook","TikTok","X","YouTube Shorts","YouTube"];
const PILARES = ["P1 – Curaduría","P2 – Planes","P3 – Experiencia","P4 – Servicio","P5 – Prueba social","P6 – Cultura"];
const FORMATOS = ["Post estático","Carrusel","Reel","Reel corto","Story interactiva","Story estática","Story","Video","YouTube Short","Live"];
const ESTADOS = ["Pendiente","En producción","Publicado"];
const DIAS_SEMANA = ["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"];
const ADMIN_PASS = "Teatrando2026Amaya";
const TIPO_COLOR = {"RESENA":"#7c3aed","FRASE":"#b45309","RECOMENDACION":"#059669","ESTRENO":"#dc2626","VACACIONES":"#0e7490"};
const PILAR_COLOR = {"P1 – Curaduría":"#C40803","P2 – Planes":"#8B0000","P3 – Experiencia":"#B61220","P4 – Servicio":"#1a1a2e","P5 – Prueba social":"#0d2137","P6 – Cultura":"#700B15"};
const RED_ICON = {"Instagram Feed":"📸","Instagram Stories":"📲","Instagram Reels":"🎬","Facebook":"👍","TikTok":"🎵","X":"✖","YouTube Shorts":"▶","YouTube":"🎥"};
const RED_COLOR = {"Instagram Feed":"#E1306C","Instagram Stories":"#833AB4","Instagram Reels":"#405DE6","Facebook":"#1877F2","TikTok":"#ff0050","X":"#ffffff","YouTube Shorts":"#FF0000","YouTube":"#FF0000"};
const ESTADO_CFG = {"Pendiente":{color:"#f59e0b",bg:"#2a1f00"},"En producción":{color:"#3b82f6",bg:"#001a2a"},"Publicado":{color:"#22c55e",bg:"#002a10"}};
const mkId = (pfx) => `${pfx}_${Date.now()}_${Math.random().toString(36).slice(2,6)}`;
const buildPub = (o={}) => ({id:mkId("p"),fecha:"",dia:"",mes:"Agosto",semana:1,pub:1,redes:["Instagram Feed","Facebook"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"",tema:"",copy:"",cta:"Link en bio",estado:"Pendiente",notas:"",linkDiseno:"",disenho:"",...o});
const buildResena = (o={}) => ({id:mkId("r"),semana:1,obra:"",titulo:"",...o});
let _historial = [];
const regCambio = (id,campo,ant,nuevo) => { _historial = [{ts:new Date().toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit",second:"2-digit"}),id,campo,anterior:typeof ant==="object"?JSON.stringify(ant):String(ant),nuevo:typeof nuevo==="object"?JSON.stringify(nuevo):String(nuevo)},..._historial].slice(0,300); return [..._historial]; };
const POLL_INTERVAL = 4000;
async function saveData(data) { try { const res = await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:JSON.stringify(data)})}); return res.ok; } catch(e) { return false; } }
async function loadData() { try { const res = await fetch('/api/data'); const json = await res.json(); if (json.data && json.data !== '{}') return JSON.parse(json.data); } catch(e) {} return null; }
const buildCoberturasAgosto = () => [
  {id:"cob_01",obra:"El Charco Inútil",recinto:"Teatro Helénico",fecha:"Jue 6 agosto",genero:"Drama / Monólogo",notas:"Humberto Dupeyron. Teatro independiente."},
  {id:"cob_02",obra:"Método de Gronholm",recinto:"Teatro Xola",fecha:"Dom 9 agosto",genero:"Suspenso",notas:"No está a la venta en Teatrando pero sacamos contenido."},
  {id:"cob_03",obra:"Afterglow",recinto:"Virginia Fábregas",fecha:"Sáb 15 agosto",genero:"Drama",notas:"Nueva sede, nueva temporada."},
  {id:"cob_04",obra:"El Deseo de lo Prohibido",recinto:"Teatro Renacimiento",fecha:"Dom 16 agosto",genero:"Drama / Thriller",notas:""},
];
const BRIEFING_AGOSTO = `📌 LÍNEA EDITORIAL AGOSTO 2026 (1-16)

Agosto arranca con las últimas semanas de vacaciones de verano, el eje central de toda la quincena. Las vacaciones terminan el 28 de agosto, lo que genera urgencia: es el último momento para aprovechar la cartelera antes de que regrese la rutina, el trabajo y la agenda apretada.

El contenido de estas dos semanas habla a ese espectador que sabe que le queda poco tiempo libre y todavía tiene obras pendientes. La comunicación mezcla recomendaciones curadas, urgencias de cierre de temporada, coberturas propias de obras visitadas en persona, y posts de humor cotidiano.`;
const buildResenasAgosto = () => [
{id:"ra_01",semana:1,obra:"El Charco Inútil",titulo:"Teatro que confronta en el Helénico — y eso es exactamente lo que debe hacer"},
{id:"ra_02",semana:1,obra:"Afterglow",titulo:"De regreso en Virginia Fábregas y más poderosa que nunca"},
{id:"ra_03",semana:1,obra:"El Sótano",titulo:"La experiencia que no se puede spoilear — solo vivir"},
{id:"ra_04",semana:1,obra:"La Dama de Negro",titulo:"El suspenso que te sigue hasta casa — y no te suelta"},
{id:"ra_05",semana:1,obra:"5 obras infantiles para ver en familia este verano en CDMX",titulo:"La guía que ningún papá debería perderse este agosto"},
{id:"ra_06",semana:1,obra:"Las mejores comedias de la cartelera de agosto",titulo:"Reír también es una forma de vivir el teatro"},
{id:"ra_07",semana:1,obra:"Y Llegaron las Brujas",titulo:"Terror teatral en el Centro Roldán que no te deja dormir"},
{id:"ra_08",semana:1,obra:"El Helénico y el Foro Shakespeare, los recintos que tienes que conocer este agosto",titulo:"Dos espacios, dos mundos, una sola ciudad"},
{id:"ra_09",semana:1,obra:"Ride the Cyclone el Musical",titulo:"El musical que nadie más se atreve a hacer — y por eso es imprescindible"},
{id:"ra_10",semana:1,obra:"Por qué el teatro es el mejor plan para cerrar las vacaciones de verano",titulo:"El argumento definitivo para una última función antes de que regrese la rutina"},
{id:"ra_11",semana:2,obra:"Método de Gronholm",titulo:"Suspenso corporativo que no te suelta desde la primera escena"},
{id:"ra_12",semana:2,obra:"El Deseo de lo Prohibido",titulo:"Pasión y secretos en un escenario que no da respiro"},
{id:"ra_13",semana:2,obra:"La Obscenidad de la Carne",titulo:"Teatro que dice lo que nadie más se atreve — y eso lo hace necesario"},
{id:"ra_14",semana:2,obra:"Las Leonas",titulo:"Fuerza femenina que quita el aliento desde la primera escena"},
{id:"ra_15",semana:2,obra:"Notre Dame de París en agosto, por qué no puedes perderte estas funciones",titulo:"Fechas únicas en el Rafael Solana que no se repetirán"},
{id:"ra_16",semana:2,obra:"Sor-presas Amén",titulo:"Humor que no falla — semana tras semana el teatro sigue lleno"},
{id:"ra_17",semana:2,obra:"3 obras de suspenso que tienes que ver antes de que termine el verano",titulo:"La Dama de Negro, El Sótano y El Charco Inútil — el trío que no perdona"},
{id:"ra_18",semana:2,obra:"El Gorila",titulo:"Humberto Dupeyron y Kafka en una sola noche en el Wilberto Cantón"},
{id:"ra_19",semana:2,obra:"Teatro independiente en CDMX, 4 opciones que nadie más te recomienda",titulo:"Más allá de los grandes recintos — el teatro que realmente arriesga"},
{id:"ra_20",semana:2,obra:"Las últimas semanas de verano, guía definitiva de teatro en CDMX agosto 2026",titulo:"Todo lo que no puedes perderte antes del 28 de agosto"},
];
const buildAgosto = () => [
{id:"ago_s1_01",fecha:"Sáb 1",dia:"Sábado",mes:"Agosto",semana:1,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"RECOMENDACION",tema:"El Gorila, monólogo de Humberto Dupeyron basado en Kafka",copy:"🦍 Un simio comparece ante ustedes para rendir cuentas.\n\nCada gesto refinado. Cada reverencia aprendida.\nY una pregunta que no deja de crecer: ¿quién domesticó a quién? 👀\n\nEl Gorila\nHumberto Dupeyron en un monólogo basado en Kafka.\nDesde 1989 — y sigue sin tener respuesta fácil. 🎭\n\n📍 Teatro Wilberto Cantón\n🗓️ Sábados 6pm\n🎟️ Reserva ya en teatrando.com.mx\n\n#Teatrando #ObrasDeCDMX #TeatroCDMX #NocheDePlan #QueHacerEnCDMX",estado:"Publicado",notas:"YA PUBLICADO",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s1_02",fecha:"Sáb 1",dia:"Sábado",mes:"Agosto",semana:1,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P2 – Planes",formato:"Post estático",tipo:"VACACIONES",tema:"El verano teatral continúa, disfruta de la programación veraniega",copy:"El verano teatral continúa. 🌞🎭\n\nAgosto arranca con la cartelera más completa del año.\nVacaciones de verano siguen — y los escenarios no descansan.\n\nEsta es tu última quincena para aprovechar el verano completo.\n¿Ya tienes tu obra de agosto?\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #VacacionesDeVerano #ObrasDeCDMX #CarteleraCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"ago_s1_03",fecha:"Dom 2",dia:"Domingo",mes:"Agosto",semana:1,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P1 – Curaduría",formato:"Carrusel",tipo:"RECOMENDACION",tema:"Recomendación semanal obras imperdibles esta semana en CDMX",copy:"LA RECOMENDACIÓN TEATRANDO DE ESTA SEMANA 🎭\n\n😱 EL SÓTANO\nLa experiencia que no se puede spoilear — solo vivir.\n📍 Teatro Fernando Soler · Vie 7 y 9:15pm · Sáb 6 y 8:30pm · Dom 5 y 7:30pm\n\n🎵 AFTERGLOW\nDe regreso en nueva sede. Más intensa que nunca.\n📍 Virginia Fábregas · Vie 9pm · Sáb 8pm · Dom 7pm\n\n🖤 LA DAMA DE NEGRO\nEl suspenso que te sigue hasta casa.\n📍 Teatro 11 de Julio · Vie 8:30pm · Sáb 6 y 8:30pm · Dom 6pm\n\n🎵 RIDE THE CYCLONE\nEl musical más original de CDMX. Todos los martes.\n📍 Teatro Xola · Mar 8:30pm\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #CarteleraCDMX #RecomendacionTeatrando",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s1_04",fecha:"Dom 2",dia:"Domingo",mes:"Agosto",semana:1,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"FRASE",tema:"Frase de la semana",copy:"'La creatividad es la inteligencia divirtiéndose.' 🎭✨\n— Albert Einstein\n\nY nosotros nos tomamos muy en serio divertirnos.\nTe esperamos en el teatro.\n\n#Teatrando #FraseDeTeatro #TeatroCDMX #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"ago_s1_05",fecha:"Lun 3",dia:"Lunes",mes:"Agosto",semana:1,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"",tema:"Perfume de Gardenia termina el sábado 8, últimas funciones",copy:"⏰ Te quedan 5 días.\n\n🌹 PERFUME DE GARDENIA\n\nUna de las obras más queridas de la cartelera cierra temporada este sábado 8.\nSi la tenías pendiente — esta semana o nunca.\n\n📍 Teatro San Rafael\n🗓️ Sáb 8 · 6 y 9:15pm — ÚLTIMAS FUNCIONES\n🎟️ teatrando.com.mx\n\n#Teatrando #PerfumeDeGardenia #TeatroCDMX #UltimasFunciones #ObrasDeCDMX",estado:"Pendiente",notas:"Termina sábado 8 agosto",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s1_06",fecha:"Lun 3",dia:"Lunes",mes:"Agosto",semana:1,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"",tema:"Por órdenes de RH nos fuimos al teatro",copy:"Por órdenes de Recursos Humanos,\nnos fuimos al teatro. 🎭\n\nHay juntas que pueden esperar.\nUna buena obra, no siempre.\n\n¿Qué función te haría abandonar la oficina hoy?\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #NocheDePlan #QueHacerEnCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"ago_s1_07",fecha:"Mar 4",dia:"Martes",mes:"Agosto",semana:1,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"",tema:"Plan de pareja Afterglow Entre Tú y Yo y El Deseo de lo Prohibido",copy:"El plan de pareja perfecto para este agosto. 💑🎭\n\n🎵 AFTERGLOW — teatro que te sacude desde adentro\n📍 Virginia Fábregas · Vie 9pm · Sáb 8pm · Dom 7pm\n\n💑 ENTRE TÚ Y YO — cuando el amor se complica en el escenario\n📍 Teatro Renacimiento · Jue 8:30pm\n\n🔥 EL DESEO DE LO PROHIBIDO — pasión y secretos sin tregua\n📍 Teatro Renacimiento · Vie 8:40pm · Dom 7pm\n\nDesliza y elige el tuyo.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PlanDePareja #ObrasDeCDMX #VacacionesDeVerano",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s1_08",fecha:"Mar 4",dia:"Martes",mes:"Agosto",semana:1,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"",tema:"Mi cuenta bancaria dijo no Teatrando dijo hay descuento",copy:"Mi cuenta bancaria dijo no.\nTeatrando dijo: hay descuento. 🎭💸\n\nEl drama debe estar en el escenario,\nno en tu estado de cuenta.\n\nEncuentra funciones con descuento\ny disfruta más teatro por menos.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #DescuentosTeatro #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"ago_s1_09",fecha:"Mié 5",dia:"Miércoles",mes:"Agosto",semana:1,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P6 – Cultura",formato:"Post estático",tipo:"",tema:"El Charco Inútil en el Helénico teatro independiente que tienes que conocer",copy:"Hay teatro que no te entretiene. 🎭\nTe confronta.\n\n🎭 EL CHARCO INÚTIL\n\nTeatro Helénico — uno de los recintos más importantes de CDMX.\nUna obra que hace preguntas que no tienen respuesta fácil.\n\n📍 Teatro Helénico\n🗓️ Jue y Vie 8pm · Sáb 7pm · Dom 6pm\n🎟️ teatrando.com.mx\n\n#Teatrando #ElCharcoInutil #TeatroCDMX #TeatroIndependiente #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s1_10",fecha:"Mié 5",dia:"Miércoles",mes:"Agosto",semana:1,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"",tema:"Notre Dame de París regresa funciones en agosto Teatro Rafael Solana",copy:"⏰ Agenda esto ahora.\n\n🔔 NOTRE DAME DE PARÍS\n\nEl musical más épico de la cartelera regresa a Teatro Rafael Solana.\n\nAmor, tragedia y la música que ya tienes en la cabeza.\n\n📍 Teatro Rafael Solana\n🗓️ Vie 14 agosto 8:30pm · Dom 16 agosto 12pm\n\nConsigue tus boletos antes de que se agoten.\n🎟️ teatrando.com.mx\n\n#Teatrando #NotreDame #TeatroCDMX #Musical #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s1_11",fecha:"Jue 6",dia:"Jueves",mes:"Agosto",semana:1,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"",tema:"Cartelera fin de semana 7-9 agosto",copy:"¿Ya tienes tu plan del fin? 🎭\n\n😱 EL SÓTANO · Vie-Dom · Teatro Fernando Soler\n🌹 PERFUME DE GARDENIA · Sáb 8 ÚLTIMA FUNCIÓN · Teatro San Rafael\n🖤 LA DAMA DE NEGRO · Vie-Dom · Teatro 11 de Julio\n🎵 AFTERGLOW · Vie 9pm · Sáb 8pm · Dom 7pm · Virginia Fábregas\n😂 SOR-PRESAS AMÉN · Vie-Dom · Teatro Hidalgo\n👑 LAS LEONAS · Sáb-Dom · Teatro México\n🎤 RISA Y TONIC · Vie-Sáb · Foro Shakespeare\n😂 ME DA PENA MI EX · Vie 8:45pm · Foro Lenin\n\nDesliza y elige.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PlanFinDeSemana #ObrasDeCDMX #CarteleraCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s1_12",fecha:"Jue 6",dia:"Jueves",mes:"Agosto",semana:1,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"VACACIONES",tema:"Plan familiar este fin de semana obras infantiles en cartelera",copy:"Plan familiar para este fin. 🌞👨‍👩‍👧🎭\n\n🧚 PETER PAN · Dom 4pm · Centro Roldán Sandoval\n🐱 CAPERUCITA ROJA · Dom 2:30 y 4:30pm · Foro Ricardo Villareal\n🐉 DRAGONCITO QUE NO SABÍA RUGIR · Dom 12pm · Talón de Asfalto\n🎭 BENITO TAMBIÉN PUEDE · Sáb 2pm · Talón de Asfalto\n🎵 DESCUBRIENDO A CRI CRI · Dom 1pm · Teatro Hidalgo\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroInfantil #TeatroCDMX #VacacionesDeVerano #PlanFamiliar",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s1_13",fecha:"Vie 7",dia:"Viernes",mes:"Agosto",semana:1,pub:1,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P1 – Curaduría",formato:"Reel",tipo:"",tema:"Cobertura El Charco Inútil reel post función Teatro Helénico",copy:"Fui a ver El Charco Inútil en el Teatro Helénico. 🎭\n\nY salí con más preguntas de las que entré.\n\nEso es lo que hace el buen teatro.\nNo te da respuestas. Te obliga a buscarlas.\n\nHumberto Dupeyron en un monólogo que no te suelta.\n\n¿Ya la viste?\n🎟️ teatrando.com.mx\n\n#Teatrando #ElCharcoInutil #TeatroHelénico #TeatroCDMX #ObrasDeCDMX",estado:"Pendiente",notas:"Aarón fue el jue 6",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s1_14",fecha:"Vie 7",dia:"Viernes",mes:"Agosto",semana:1,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"",tema:"Perfume de Gardenia mañana última función última oportunidad",copy:"⏰ MAÑANA ES EL ÚLTIMO DÍA.\n\n🌹 PERFUME DE GARDENIA\n\nMañana sábado 8 es la última función.\nSi la tenías pendiente — mañana es la última oportunidad.\n\n📍 Teatro San Rafael\n🗓️ Sáb 8 · 6 y 9:15pm\n🎟️ teatrando.com.mx\n\n#Teatrando #PerfumeDeGardenia #TeatroCDMX #UltimaFuncion #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s1_15",fecha:"Sáb 8",dia:"Sábado",mes:"Agosto",semana:1,pub:1,redes:["Instagram Feed","Facebook","X"],pilar:"P5 – Prueba social",formato:"Post estático",tipo:"",tema:"¿Cuál es tu plan estas últimas semanas de vacaciones de verano?",copy:"Últimas semanas de vacaciones. 🌞\n\n¿Cuál es tu plan?\n\n🎭 Ya tengo mi obra de agosto comprada\n🏖️ Me voy de viaje y busco teatro en otra ciudad\n😴 Tenía plan de ir pero sigo postponiendo\n🤔 Todavía no sé qué ver\n\n¿Cuál eres tú?\nCuéntanos en los comentarios 👇\n\n#Teatrando #TeatroCDMX #VacacionesDeVerano #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"ago_s1_16",fecha:"Sáb 8",dia:"Sábado",mes:"Agosto",semana:1,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"",tema:"El grupo fue abandonado todos se fueron al teatro",copy:"El grupo fue abandonado.\nTodos se fueron al teatro. 🎭\n\nCuando la cartelera está buena,\nhasta el grupo más activo desaparece.\n\n📵 Menos mensajes.\n🎭 Más emociones en vivo.\n\n¿Cuál fue la última obra que te dejó sin palabras?\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #NocheDePlan",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"ago_s1_17",fecha:"Dom 9",dia:"Domingo",mes:"Agosto",semana:1,pub:1,redes:["Instagram Feed","Facebook","X"],pilar:"P1 – Curaduría",formato:"Carrusel",tipo:"RESENA",tema:"Reseña El Charco Inútil teatro que confronta en el Helénico",copy:"El Charco Inútil no es una obra cómoda. 🎭\n\nY eso es exactamente lo que la hace imprescindible.\n\nHumberto Dupeyron construye un monólogo donde cada palabra pesa.\nDonde el silencio también actúa.\n\nFuimos a verla. Y salimos distintos.\n\n📍 Teatro Helénico\n🗓️ Jue y Vie 8pm · Sáb 7pm · Dom 6pm\n🎟️ teatrando.com.mx\n\n#Teatrando #ElCharcoInutil #TeatroHelénico #TeatroCDMX #ReseñaTeatro",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s1_18",fecha:"Dom 9",dia:"Domingo",mes:"Agosto",semana:1,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"",tema:"Ride the Cyclone mañana martes en Teatro Xola consigue boletos",copy:"Mañana martes en Teatro Xola. 🎵🎭\n\n🎡 RIDE THE CYCLONE — 2DA TEMPORADA\n\nEl musical más original y sorprendente de la cartelera.\n\nSi no la has visto — mañana es el día.\nSi ya la viste — ya sabes que vale volver.\n\n📍 Teatro Xola · Mar 10 · 8:30pm\n🎟️ teatrando.com.mx\n\n#Teatrando #RideTheCyclone #TeatroCDMX #Musical #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s2_01",fecha:"Lun 10",dia:"Lunes",mes:"Agosto",semana:2,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P1 – Curaduría",formato:"Carrusel",tipo:"RECOMENDACION",tema:"Recomendación semanal obras destacadas semana 2 agosto",copy:"LA RECOMENDACIÓN TEATRANDO DE ESTA SEMANA 🎭\n\n🎭 EL CHARCO INÚTIL — teatro que confronta en el Helénico\n📍 Teatro Helénico · Jue y Vie 8pm · Sáb 7pm · Dom 6pm\n\n👑 LAS LEONAS — fuerza femenina que no da tregua\n📍 Teatro México · Sáb 6 y 8:30pm · Dom 5 y 7pm\n\n🖤 LA OBSCENIDAD DE LA CARNE — teatro que dice lo que nadie más se atreve\n📍 Teatro Renacimiento · Vie 6:40pm · Sáb 5:40 y 8pm · Dom 4:40pm\n\n🎵 NOVICIA REBELDE — solo hasta el jueves 14\n📍 Teatro Xola · Mar-Jue · ÚLTIMAS FUNCIONES\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #CarteleraCDMX #RecomendacionTeatrando",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s2_02",fecha:"Lun 10",dia:"Lunes",mes:"Agosto",semana:2,pub:2,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P1 – Curaduría",formato:"Reel",tipo:"",tema:"Cobertura Método de Gronholm reel post función",copy:"Fui a ver Método de Gronholm. 🎭\n\nUna sala de juntas. Cuatro candidatos.\nY un juego que nadie sabe exactamente cuándo empieza.\n\nEl teatro de suspenso en su forma más inteligente.\nCada escena te hace dudar de alguien diferente.\n\nSalí pensando en esto durante días.\n\n📍 Teatro Xola · Vie 8pm · Sáb 7pm · Dom 6pm\n🎟️ teatrando.com.mx\n\n#Teatrando #MetodoDeGronholm #TeatroCDMX #TeatroDeSuspenso #ObrasDeCDMX",estado:"Pendiente",notas:"Aarón fue el dom 9",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s2_03",fecha:"Mar 11",dia:"Martes",mes:"Agosto",semana:2,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"",tema:"Novicia Rebelde termina el jueves 14 últimas 3 funciones",copy:"⏰ ÚLTIMAS 3 FUNCIONES.\n\n🎵 NOVICIA REBELDE\n\nUno de los musicales más queridos de la cartelera\ncierra temporada este jueves 14.\n\nSi la tenías pendiente — ya no hay más tiempo.\n\n📍 Teatro Xola · Mar 11 · Mié 12 · Jue 13 · 8pm\n🎟️ teatrando.com.mx\n\n#Teatrando #NoviciaRebelde #TeatroCDMX #UltimasFunciones #Musical",estado:"Pendiente",notas:"Termina jueves 14 agosto",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s2_04",fecha:"Mar 11",dia:"Martes",mes:"Agosto",semana:2,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"",tema:"Se pospone el estrés hoy hay función",copy:"Se pospone el estrés.\nHoy hay función. 🎭\n\nLa terapia viene en muchos formatos.\nAlgunas duran 90 minutos\ny terminan con aplausos. 👏\n\n¿Comedia, drama o musical?\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #ObrasDeCDMX #NocheDePlan #QueHacerEnCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"ago_s2_05",fecha:"Mié 12",dia:"Miércoles",mes:"Agosto",semana:2,pub:1,redes:["Instagram Feed","Facebook","X"],pilar:"P1 – Curaduría",formato:"Carrusel",tipo:"RESENA",tema:"Reseña Método de Gronholm publicada",copy:"Método de Gronholm no es solo suspenso. 🎭\n\nEs un espejo.\nCada personaje representa algo que reconoces.\nCada mentira tiene una verdad detrás.\n\nTeatro que te obliga a pensar.\nY eso es exactamente lo que debe hacer.\n\nLee la reseña completa en teatrando.com.mx\n\n📍 Teatro Xola · Vie 8pm · Sáb 7pm · Dom 6pm\n🎟️ teatrando.com.mx\n\n#Teatrando #MetodoDeGronholm #TeatroCDMX #ReseñaTeatro #TeatroDeSuspenso",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s2_06",fecha:"Mié 12",dia:"Miércoles",mes:"Agosto",semana:2,pub:2,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P6 – Cultura",formato:"Carrusel",tipo:"",tema:"Los géneros del teatro ¿cuál es el tuyo?",copy:"¿Sabes qué tipo de teatro te gusta? 🎭\n\nHay un mundo más allá del musical:\n\n😂 COMEDIA — para reír de lo que reconoces\n😱 SUSPENSO — para no dormir esa noche\n🎵 MUSICAL — para que la música cuente la historia\n🖤 DRAMA — para sentir lo que no puedes decir\n🎩 MONÓLOGO — para escuchar una sola voz que lo dice todo\n\nEste agosto prueba uno que no hayas visto.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #GenerosDelTeatro #VacacionesDeVerano #CulturaTeatro",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s2_07",fecha:"Jue 13",dia:"Jueves",mes:"Agosto",semana:2,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories","Facebook Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"",tema:"Cartelera fin de semana 14-16 agosto",copy:"¿Ya tienes tu plan del fin? 🎭\n\n😱 EL SÓTANO · Vie-Dom · Teatro Fernando Soler\n🖤 LA DAMA DE NEGRO · Vie-Dom · Teatro 11 de Julio\n🎵 AFTERGLOW · Vie 9pm · Sáb 8pm · Dom 7pm · Virginia Fábregas\n👑 LAS LEONAS · Sáb-Dom · Teatro México\n😂 SOR-PRESAS AMÉN · Vie-Dom · Teatro Hidalgo\n🔥 EL DESEO DE LO PROHIBIDO · Vie 8:40pm · Dom 7pm · Teatro Renacimiento\n🎵 NOTRE DAME DE PARÍS · Vie 14 8:30pm · Dom 16 12pm · Teatro Rafael Solana\n🎤 RISA Y TONIC · Vie-Sáb · Foro Shakespeare\n🎭 EL CHARCO INÚTIL · Vie 8pm · Sáb 7pm · Dom 6pm · Teatro Helénico\n\nDesliza y elige.\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #PlanFinDeSemana #ObrasDeCDMX #CarteleraCDMX",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s2_08",fecha:"Jue 13",dia:"Jueves",mes:"Agosto",semana:2,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P2 – Planes",formato:"Carrusel",tipo:"VACACIONES",tema:"Plan familiar este fin de semana obras infantiles agosto",copy:"Plan familiar para este fin. 🌞👨‍👩‍👧🎭\n\n🧚 PETER PAN · Dom 4pm · Centro Roldán Sandoval\n🐱 CAPERUCITA ROJA · Dom 2:30 y 4:30pm · Foro Ricardo Villareal\n🎵 DESCUBRIENDO A CRI CRI · Dom 1pm · Teatro Hidalgo\n👑 EL PRINCIPITO · Dom 1pm · Teatro Varsovia\n🐉 DRAGONCITO QUE NO SABÍA RUGIR · Dom 12pm · Talón de Asfalto\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroInfantil #TeatroCDMX #VacacionesDeVerano #PlanFamiliar",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s2_09",fecha:"Vie 14",dia:"Viernes",mes:"Agosto",semana:2,pub:1,redes:["Instagram Feed","Facebook","X","Instagram Stories"],pilar:"P1 – Curaduría",formato:"Post estático",tipo:"RECOMENDACION",tema:"Afterglow mañana sábado 15 consigue tus boletos hoy",copy:"⏰ Mañana sábado.\n\n🎵 AFTERGLOW\n\nDe regreso en nueva sede — Virginia Fábregas.\nMás intensa. Más íntima. Más poderosa.\n\nConsigue tus boletos hoy antes de que se agoten.\n\n📍 Virginia Fábregas · Sáb 15 · 8pm\n🎟️ teatrando.com.mx\n\n#Teatrando #Afterglow #TeatroCDMX #ObrasDeCDMX #RecomendacionTeatrando",estado:"Pendiente",notas:"",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s2_10",fecha:"Vie 14",dia:"Viernes",mes:"Agosto",semana:2,pub:2,redes:["Instagram Feed","Facebook","Instagram Stories"],pilar:"P3 – Experiencia",formato:"Post estático",tipo:"FRASE",tema:"Frase de la semana",copy:"'La tierra es un teatro, pero tiene un reparto deplorable.' 🎭✨\n— Oscar Wilde\n\nNosotros nos encargamos de mejorar el reparto.\nTe esperamos en la butaca.\n\n#Teatrando #FraseDeTeatro #TeatroCDMX #ObrasDeCDMX",estado:"Pendiente",notas:"",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"ago_s2_11",fecha:"Sáb 15",dia:"Sábado",mes:"Agosto",semana:2,pub:1,redes:["Instagram Reels","TikTok","Instagram Stories"],pilar:"P3 – Experiencia",formato:"Reel",tipo:"",tema:"Anticipo cobertura Afterglow esta noche voy a Virginia Fábregas",copy:"Esta noche voy a ver Afterglow. 🎵🎭\n\nNueva sede — Virginia Fábregas.\nNueva temporada.\nMisma historia que no te suelta.\n\nNos vemos del otro lado.\n\n📍 Virginia Fábregas · Esta noche 8pm\n🎟️ teatrando.com.mx\n\n#Teatrando #Afterglow #TeatroCDMX #ObrasDeCDMX #CoberturaTeatrando",estado:"Pendiente",notas:"Aarón va esta noche",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s2_12",fecha:"Sáb 15",dia:"Sábado",mes:"Agosto",semana:2,pub:2,redes:["Instagram Feed","Facebook","X"],pilar:"P2 – Planes",formato:"Post estático",tipo:"VACACIONES",tema:"Últimas semanas de vacaciones de verano aprovecha el teatro",copy:"Quedan dos semanas de vacaciones. ⏰🌞\n\nAntes de que regrese la rutina,\nla agenda de trabajo,\nlos lunes que no perdonan...\n\nHaz espacio para una función más.\n\nEl teatro no espera.\nLas vacaciones tampoco.\n\n🎟️ teatrando.com.mx\n\n#Teatrando #TeatroCDMX #VacacionesDeVerano #ObrasDeCDMX #UltimasSemanas",estado:"Pendiente",notas:"Vacaciones terminan 28 agosto",disenho:"para_disenar",cta:"teatrando.com.mx"},
{id:"ago_s2_13",fecha:"Dom 16",dia:"Domingo",mes:"Agosto",semana:2,pub:1,redes:["Instagram Reels","TikTok","YouTube Shorts"],pilar:"P1 – Curaduría",formato:"Reel",tipo:"",tema:"Cobertura Afterglow reel post función Virginia Fábregas",copy:"Fui a ver Afterglow. 🎵🎭\n\nY Virginia Fábregas le queda perfecto a esta historia.\n\nEs una obra sobre lo que no se dice.\nSobre lo que se deja ir.\nSobre lo que regresa aunque no quieras.\n\nSalí en silencio. Eso siempre es buena señal.\n\n📍 Virginia Fábregas · Vie 9pm · Sáb 8pm · Dom 7pm\n🎟️ teatrando.com.mx\n\n#Teatrando #Afterglow #TeatroCDMX #ObrasDeCDMX #CoberturaTeatrando",estado:"Pendiente",notas:"Aarón fue el sáb 15",disenho:"",cta:"teatrando.com.mx"},
{id:"ago_s2_14",fecha:"Dom 16",dia:"Domingo",mes:"Agosto",semana:2,pub:2,redes:["Instagram Reels","TikTok","Instagram Stories"],pilar:"P3 – Experiencia",formato:"Reel",tipo:"",tema:"Anticipo cobertura El Deseo de lo Prohibido esta noche voy al Teatro Renacimiento",copy:"Esta noche voy a ver El Deseo de lo Prohibido. 🔥🎭\n\nTeatro Renacimiento.\nPasión. Secretos. Un escenario que no da respiro.\n\nNos vemos del otro lado.\n\n📍 Teatro Renacimiento · Esta noche\n🎟️ teatrando.com.mx\n\n#Teatrando #ElDeseoDeLoProhibido #TeatroCDMX #ObrasDeCDMX #CoberturaTeatrando",estado:"Pendiente",notas:"Aarón va esta noche",disenho:"",cta:"teatrando.com.mx"},
];
export default function App() {
  const isMounted = useRef(true);
  const modoClienteRef = useRef(true);
  const saveTimerRef = useRef(null);
  const [parrillas,setParrillas] = useState({"Agosto":buildAgosto()});
  const [resenas,setResenas] = useState({"Agosto":buildResenasAgosto()});
  const [briefings,setBriefings] = useState({"Agosto":BRIEFING_AGOSTO});
  const [coberturas,setCoberturas] = useState(buildCoberturasAgosto());
  const [semanaActiva,setSemanaActiva] = useState(1);
  const [cardAbierta,setCardAbierta] = useState(null);
  const [filtros,setFiltros] = useState({pilar:"Todos",formato:"Todos"});
  const [vista,setVista] = useState("parrilla");
  const [vistaCliente,setVistaCliente] = useState("parrilla");
  const [notifMsg,setNotifMsg] = useState("");
  const [generando,setGenerando] = useState({});
  const [syncStatus,setSyncStatus] = useState("idle");
  const [lastRefresh,setLastRefresh] = useState("");
  const [modoCliente,setModoCliente] = useState(true);
  const [showAdminLogin,setShowAdminLogin] = useState(false);
  const [passInput,setPassInput] = useState("");
  const [passError,setPassError] = useState(false);
  const [modalAgregarDia,setModalAgregarDia] = useState(false);
  const [nuevoDiaForm,setNuevoDiaForm] = useState({fecha:"",dia:"Lunes",semana:1,numPubs:2,tipo:""});
  const [editandoBriefing,setEditandoBriefing] = useState(false);
  const [marcandoId,setMarcandoId] = useState(null);
  const [editandoFechaId,setEditandoFechaId] = useState(null);
  const [nuevaFecha,setNuevaFecha] = useState("");
  const mes="Agosto";
  const parrilla=parrillas[mes]||[];
  const resenasMes=resenas[mes]||[];
  const briefingMes=briefings[mes]||"";
  const semanasDelMes=[...new Set(parrilla.map(p=>p.semana))].sort((a,b)=>a-b);
  const notif=(msg)=>{setNotifMsg(msg);setTimeout(()=>setNotifMsg(""),2800);};
  const doLogin=()=>{if(passInput===ADMIN_PASS){setModoCliente(false);modoClienteRef.current=false;setShowAdminLogin(false);setPassInput("");setPassError(false);}else setPassError(true);};
  const doLogout=()=>{setModoCliente(true);modoClienteRef.current=true;};
  useEffect(()=>{isMounted.current=true;(async()=>{const saved=await loadData();if(saved&&isMounted.current){if(saved.parrillas)setParrillas(saved.parrillas);if(saved.resenas)setResenas(saved.resenas);if(saved.briefings)setBriefings(saved.briefings);if(saved.coberturas)setCoberturas(saved.coberturas);}})();return()=>{isMounted.current=false;};},[]);
  const guardarAdmin=useCallback(async(data)=>{if(modoClienteRef.current)return;if(saveTimerRef.current)clearTimeout(saveTimerRef.current);setSyncStatus("saving");saveTimerRef.current=setTimeout(async()=>{const ok=await saveData(data);if(isMounted.current){setSyncStatus(ok?"saved":"error");setTimeout(()=>{if(isMounted.current)setSyncStatus("idle");},2000);}},800);},[]);
  useEffect(()=>{const interval=setInterval(async()=>{if(!modoClienteRef.current)return;const saved=await loadData();if(saved&&isMounted.current){if(saved.parrillas)setParrillas(saved.parrillas);if(saved.resenas)setResenas(saved.resenas);if(saved.briefings)setBriefings(saved.briefings);if(saved.coberturas)setCoberturas(saved.coberturas);setLastRefresh(new Date().toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit",second:"2-digit"}));}},POLL_INTERVAL);return()=>clearInterval(interval);},[]);
  const sortP=(arr)=>[...arr].sort((a,b)=>{if(a.semana!==b.semana)return a.semana-b.semana;const nA=parseInt((a.fecha||"").replace(/\D/g,"")||"0"),nB=parseInt((b.fecha||"").replace(/\D/g,"")||"0");if(nA!==nB)return nA-nB;return(a.pub||0)-(b.pub||0);});
  const guardarTodo=(np,nr,nb,nc)=>{guardarAdmin({parrillas:np||parrillas,resenas:nr||resenas,briefings:nb||briefings,coberturas:nc||coberturas,mesesDisp:["Agosto"]});};
  const editarCampo=useCallback((id,campo,valor)=>{if(modoClienteRef.current)return;setParrillas(prev=>{const item=(prev[mes]||[]).find(p=>p.id===id);if(!item)return prev;regCambio(id,campo,item[campo],valor);let nl=prev[mes].map(p=>p.id===id?{...p,[campo]:valor}:p);if(campo==="fecha")nl=sortP(nl);const nuevo={...prev,[mes]:nl};guardarAdmin({parrillas:nuevo,resenas,briefings,coberturas,mesesDisp:["Agosto"]});return nuevo;});},[mes,resenas,briefings,coberturas,guardarAdmin]);
  const editarCampoCliente=async(id,campo,valor)=>{setMarcandoId(id);try{const saved=await loadData();if(saved&&saved.parrillas&&saved.parrillas[mes]){saved.parrillas[mes]=saved.parrillas[mes].map(p=>p.id===id?{...p,[campo]:valor}:p);const ok=await saveData(saved);if(ok&&isMounted.current)setParrillas(prev=>({...prev,[mes]:(prev[mes]||[]).map(p=>p.id===id?{...p,[campo]:valor}:p)}));}else{setParrillas(prev=>{const nuevo={...prev,[mes]:(prev[mes]||[]).map(p=>p.id===id?{...p,[campo]:valor}:p)};saveData({parrillas:nuevo,resenas,briefings,coberturas,mesesDisp:["Agosto"]});return nuevo;});}}catch(e){}setMarcandoId(null);};
  const toggleRed=useCallback((id,red)=>{if(modoClienteRef.current)return;setParrillas(prev=>{const item=(prev[mes]||[]).find(p=>p.id===id);if(!item)return prev;const nv=item.redes.includes(red)?item.redes.filter(r=>r!==red):[...item.redes,red];const nuevo={...prev,[mes]:prev[mes].map(p=>p.id===id?{...p,redes:nv}:p)};guardarAdmin({parrillas:nuevo,resenas,briefings,coberturas,mesesDisp:["Agosto"]});return nuevo;});},[mes,resenas,briefings,coberturas,guardarAdmin]);
  const editarResena=useCallback((id,campo,valor)=>{if(modoClienteRef.current)return;setResenas(prev=>{const nuevo={...prev,[mes]:prev[mes].map(r=>r.id===id?{...r,[campo]:valor}:r)};guardarAdmin({parrillas,resenas:nuevo,briefings,coberturas,mesesDisp:["Agosto"]});return nuevo;});},[mes,parrillas,briefings,coberturas,guardarAdmin]);
  const handleEliminarPub=(id)=>{if(modoClienteRef.current)return;setParrillas(prev=>{const nuevo={...prev,[mes]:prev[mes].filter(p=>p.id!==id)};guardarAdmin({parrillas:nuevo,resenas,briefings,coberturas,mesesDisp:["Agosto"]});return nuevo;});setCardAbierta(null);notif("🗑 Publicación eliminada");};
  const handleAgregarResena=()=>{if(modoClienteRef.current)return;const nr=buildResena({semana:semanaActiva,obra:"Nueva obra"});setResenas(prev=>{const nuevo={...prev,[mes]:[...(prev[mes]||[]),nr]};guardarAdmin({parrillas,resenas:nuevo,briefings,coberturas,mesesDisp:["Agosto"]});return nuevo;});notif("✅ Reseña agregada");};
  const handleEliminarResena=(id)=>{if(modoClienteRef.current)return;setResenas(prev=>{const nuevo={...prev,[mes]:prev[mes].filter(r=>r.id!==id)};guardarAdmin({parrillas,resenas:nuevo,briefings,coberturas,mesesDisp:["Agosto"]});return nuevo;});notif("🗑 Reseña eliminada");};
  const handleAgregarDia=()=>{if(!nuevoDiaForm.fecha){notif("⚠ Escribe una fecha");return;}const pubs=[];for(let i=1;i<=nuevoDiaForm.numPubs;i++)pubs.push(buildPub({fecha:nuevoDiaForm.fecha,dia:nuevoDiaForm.dia,semana:parseInt(nuevoDiaForm.semana),pub:i,tipo:nuevoDiaForm.tipo||""}));setParrillas(prev=>{const nuevo={...prev,[mes]:sortP([...(prev[mes]||[]),...pubs])};guardarAdmin({parrillas:nuevo,resenas,briefings,coberturas,mesesDisp:["Agosto"]});return nuevo;});setModalAgregarDia(false);setNuevoDiaForm({fecha:"",dia:"Lunes",semana:1,numPubs:2,tipo:""});notif(`✅ "${nuevoDiaForm.fecha}" agregado`);};
  const marcarSemana=(estado)=>{if(modoClienteRef.current)return;setParrillas(prev=>{const nuevo={...prev,[mes]:prev[mes].map(p=>p.semana===semanaActiva?{...p,estado}:p)};guardarAdmin({parrillas:nuevo,resenas,briefings,coberturas,mesesDisp:["Agosto"]});return nuevo;});notif(`Semana ${semanaActiva} → ${estado}`);};
  const filtradas=parrilla.filter(p=>{if(p.semana!==semanaActiva)return false;if(filtros.pilar!=="Todos"&&p.pilar!==filtros.pilar)return false;if(filtros.formato!=="Todos"&&!p.formato.toLowerCase().includes(filtros.formato.toLowerCase().replace(" estático","").replace(" interactiva","")))return false;return true;});
  const byDate={};filtradas.forEach(p=>{if(!byDate[p.fecha])byDate[p.fecha]=[];byDate[p.fecha].push(p);});
  const byDateCliente={};(parrillas[mes]||[]).filter(p=>p.semana===semanaActiva).forEach(p=>{if(!byDateCliente[p.fecha])byDateCliente[p.fecha]=[];byDateCliente[p.fecha].push(p);});
  const mix=useMemo(()=>{const t=parrilla.length||1;return{p123:Math.round(parrilla.filter(p=>["P1 – Curaduría","P2 – Planes","P3 – Experiencia"].includes(p.pilar)).length/t*100),p4:Math.round(parrilla.filter(p=>p.pilar==="P4 – Servicio").length/t*100),p56:Math.round(parrilla.filter(p=>["P5 – Prueba social","P6 – Cultura"].includes(p.pilar)).length/t*100)};},[parrilla]);
  const sc=e=>ESTADO_CFG[e]||ESTADO_CFG["Pendiente"];
  const IS={width:"100%",background:"#0a0a0a",color:"#fff",border:"1px solid #1e1e1e",borderRadius:6,padding:"6px 9px",fontSize:11,boxSizing:"border-box",fontFamily:"inherit"};
  const BTN=({active,onClick,children,style={},danger=false,small=false,disabled=false})=>(<button onClick={onClick} disabled={disabled} style={{padding:small?"4px 10px":"6px 16px",borderRadius:20,border:danger?"1.5px solid #7f1d1d":(active?"2px solid #C40803":"1.5px solid #252525"),background:danger?"#2d0000":(active?"#C40803":"#111"),color:danger?"#ff6b6b":"#fff",fontWeight:700,cursor:disabled?"not-allowed":"pointer",fontSize:small?10:11,opacity:disabled?0.5:1,transition:"all 0.15s",...style}}>{children}</button>);
  const etiq=s=>s===1?"1-9 ago":s===2?"10-16 ago":"";
  if(showAdminLogin)return(<div style={{fontFamily:"Segoe UI,system-ui,sans-serif",background:"#0a0a0a",minHeight:"100vh",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{background:"#111",border:"1px solid #C40803",borderRadius:16,padding:36,width:340,maxWidth:"90vw",textAlign:"center"}}><div style={{fontSize:32,marginBottom:6}}>🎭</div><div style={{fontSize:9,color:"rgba(255,255,255,0.4)",letterSpacing:3,textTransform:"uppercase",marginBottom:4}}>Área de Administración</div><div style={{fontSize:24,fontWeight:900,color:"#C40803",marginBottom:20}}>TEATRANDO</div><input type="password" value={passInput} onChange={e=>{setPassInput(e.target.value);setPassError(false);}} onKeyDown={e=>{if(e.key==="Enter")doLogin();}} placeholder="Contraseña..." autoFocus style={{...IS,marginBottom:8,textAlign:"center",fontSize:14,letterSpacing:4}}/>{passError&&<div style={{fontSize:10,color:"#C40803",marginBottom:8}}>Contraseña incorrecta.</div>}<div style={{display:"flex",gap:8,justifyContent:"center",marginTop:8}}><BTN onClick={doLogin}>Entrar</BTN><BTN onClick={()=>{setShowAdminLogin(false);setPassInput("");setPassError(false);}} danger small>Cancelar</BTN></div></div></div>);
  if(modoCliente)return(
    <div style={{fontFamily:"Segoe UI,system-ui,sans-serif",background:"#0a0a0a",minHeight:"100vh",color:"#fff"}}>
      <div style={{background:"linear-gradient(135deg,#C40803 0%,#8B0000 60%,#0a0a0a 100%)",padding:"16px 20px",borderBottom:"2px solid #C40803"}}>
        <div style={{maxWidth:900,margin:"0 auto"}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:10,marginBottom:12}}>
            <div style={{display:"flex",alignItems:"center",gap:12}}><div style={{fontSize:26,fontWeight:900,color:"#fff",letterSpacing:-1}}>🎭 Teatrando</div><div><div style={{fontSize:8,color:"rgba(255,255,255,0.6)",letterSpacing:3,textTransform:"uppercase"}}>Propuesta de Contenido</div><div style={{fontSize:20,fontWeight:900}}>AGOSTO 2026</div></div></div>
            <BTN onClick={()=>setShowAdminLogin(true)} small style={{background:"rgba(0,0,0,0.3)",border:"1px solid rgba(255,255,255,0.2)"}}>🔐 Admin</BTN>
          </div>
          <div style={{display:"flex",alignItems:"center",gap:6,marginBottom:10}}><span style={{width:7,height:7,borderRadius:"50%",background:"#22c55e",display:"inline-block"}}/><span style={{fontSize:8,color:"rgba(255,255,255,0.5)",letterSpacing:1}}>EN VIVO · refresca cada 4s</span>{lastRefresh&&<span style={{fontSize:8,color:"rgba(255,255,255,0.3)"}}>· {lastRefresh}</span>}</div>
          <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>
            <BTN active={vistaCliente==="parrilla"} onClick={()=>setVistaCliente("parrilla")} small>📋 Parrilla</BTN>
            <BTN active={vistaCliente==="resenas"} onClick={()=>setVistaCliente("resenas")} small>📖 Reseñas</BTN>
            <BTN active={vistaCliente==="coberturas"} onClick={()=>setVistaCliente("coberturas")} small>🎭 Coberturas</BTN>
            <BTN active={vistaCliente==="bitacora"} onClick={()=>setVistaCliente("bitacora")} small>📒 Bitácora</BTN>
          </div>
        </div>
      </div>
      <div style={{maxWidth:900,margin:"0 auto",padding:"16px 14px"}}>
        <div style={{marginBottom:14,display:"flex",gap:6,flexWrap:"wrap"}}>{semanasDelMes.map(s=>(<button key={s} onClick={()=>setSemanaActiva(s)} style={{padding:"5px 14px",borderRadius:18,border:semanaActiva===s?"2px solid #C40803":"1.5px solid #222",background:semanaActiva===s?"#C40803":"#111",color:"#fff",fontWeight:700,cursor:"pointer",fontSize:10}}>S{s} <span style={{opacity:0.7}}>({etiq(s)})</span></button>))}</div>
        {briefingMes&&<div style={{background:"#111",border:"1px solid #C40803",borderRadius:10,padding:"12px 16px",marginBottom:16}}><div style={{fontSize:9,color:"#C40803",fontWeight:700,letterSpacing:2,textTransform:"uppercase",marginBottom:6}}>📋 Línea editorial Agosto</div><pre style={{fontSize:11,color:"#ccc",lineHeight:1.7,whiteSpace:"pre-wrap",fontFamily:"inherit",margin:0}}>{briefingMes}</pre></div>}
        {vistaCliente==="parrilla"&&(<><div style={{fontSize:10,color:"#444",marginBottom:12}}>{(parrillas[mes]||[]).filter(p=>p.semana===semanaActiva).length} publicaciones · <span style={{color:"#22c55e"}}>{(parrillas[mes]||[]).filter(p=>p.semana===semanaActiva&&p.estado==="Publicado").length} publicadas</span> · <span style={{color:"#3b82f6"}}>{(parrillas[mes]||[]).filter(p=>p.semana===semanaActiva&&p.estado==="En producción").length} en producción</span></div>
        {Object.entries(byDateCliente).map(([fecha,pubs])=>(<div key={fecha} style={{marginBottom:16}}><div style={{fontSize:10,color:"#C40803",fontWeight:700,marginBottom:8,display:"flex",alignItems:"center",gap:8}}><span style={{background:"#C40803",color:"#fff",padding:"2px 12px",borderRadius:5}}>{fecha}</span><div style={{flex:1,height:1,background:"#1a1a1a"}}/></div>{pubs.map(p=>{const ec=sc(p.estado);const marcando=marcandoId===p.id;return(<div key={p.id} style={{background:"#0d0d0d",border:p.disenho==="para_disenar"?"2px solid #C40803":p.disenho==="disenho_realizado"?"2px solid #059669":"1px solid #161616",borderLeft:`3px solid ${PILAR_COLOR[p.pilar]||"#333"}`,borderRadius:8,padding:"12px 14px",marginBottom:8}}>{p.disenho==="para_disenar"&&(<div style={{background:"#C40803",color:"#fff",fontSize:9,fontWeight:900,padding:"4px 12px",borderRadius:4,marginBottom:8,display:"flex",alignItems:"center",justifyContent:"space-between",letterSpacing:1}}><span>🎨 Para diseñar</span><button onClick={()=>{if(!marcando)editarCampoCliente(p.id,"disenho","disenho_realizado");}} disabled={marcando} style={{background:"#fff",color:"#C40803",border:"none",borderRadius:4,padding:"2px 10px",fontSize:8,fontWeight:900,cursor:marcando?"not-allowed":"pointer",opacity:marcando?0.6:1}}>{marcando?"Guardando...":"Marcar como realizado"}</button></div>)}{p.disenho==="disenho_realizado"&&(<div style={{background:"#059669",color:"#fff",fontSize:9,fontWeight:900,padding:"4px 12px",borderRadius:4,marginBottom:8,letterSpacing:1}}>✅ Diseño realizado</div>)}<div style={{display:"flex",gap:5,marginBottom:6,flexWrap:"wrap",alignItems:"center"}}>{p.tipo&&<span style={{fontSize:8,background:TIPO_COLOR[p.tipo]||"#555",color:"#fff",padding:"2px 8px",borderRadius:4,fontWeight:900,textTransform:"uppercase"}}>{p.tipo}</span>}<span style={{fontSize:8,color:"#fff",background:PILAR_COLOR[p.pilar]||"#333",padding:"2px 8px",borderRadius:6,fontWeight:700}}>{p.pilar}</span><span style={{fontSize:8,color:"#666"}}>{p.formato}</span><span style={{marginLeft:"auto",fontSize:10,color:ec.color,background:ec.bg,padding:"3px 12px",borderRadius:20,border:`1.5px solid ${ec.color}`,fontWeight:900}}>{p.estado}</span></div><div style={{fontSize:14,fontWeight:700,color:"#fff",marginBottom:8}}>{p.tema}</div>{p.copy&&<pre style={{fontSize:11,color:"#bbb",lineHeight:1.7,whiteSpace:"pre-wrap",fontFamily:"inherit",margin:"0 0 10px"}}>{p.copy}</pre>}<div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{(p.redes||[]).map(r=><span key={r} style={{fontSize:9,color:RED_COLOR[r]||"#aaa",background:"#1a1a1a",padding:"2px 7px",borderRadius:6}}>{RED_ICON[r]} {r}</span>)}</div>{p.notas&&p.notas!=="YA PUBLICADO"&&<div style={{fontSize:9,color:"#444",marginTop:6,fontStyle:"italic"}}>📌 {p.notas}</div>}</div>);})}</div>))}</>)}
        {vistaCliente==="resenas"&&(<div><div style={{fontSize:11,color:"#555",marginBottom:16}}>{resenasMes.length} reseñas planificadas para Agosto</div>{[1,2].map(s=>{const rs=resenasMes.filter(r=>r.semana===s);if(!rs.length)return null;return(<div key={s} style={{marginBottom:28}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><span style={{fontSize:9,color:"#fff",background:"#C40803",fontWeight:700,textTransform:"uppercase",letterSpacing:2,padding:"3px 12px",borderRadius:6}}>Semana {s}</span><div style={{flex:1,height:1,background:"#1a1a1a"}}/></div>{rs.map(r=>(<div key={r.id} style={{background:"#0d0d0d",border:"1px solid #1a1a1a",borderRadius:10,padding:"12px 14px",marginBottom:8}}><div style={{fontSize:13,fontWeight:700,color:"#fff",marginBottom:4}}>{r.obra||"Sin título"}</div>{r.titulo&&<div style={{fontSize:10,color:"#C40803",fontStyle:"italic"}}>{r.titulo}</div>}</div>))}</div>);})}</div>)}
        {vistaCliente==="coberturas"&&(<div><div style={{fontSize:11,color:"#555",marginBottom:16}}>Obras que Aarón visitará en persona este mes 🎭</div>{coberturas.map(c=>(<div key={c.id} style={{background:"#0d0d0d",border:"1px solid #161616",borderLeft:"3px solid #C40803",borderRadius:8,padding:"12px 14px",marginBottom:8}}><div style={{fontSize:14,fontWeight:700,color:"#fff",marginBottom:4}}>{c.obra}</div><div style={{fontSize:10,color:"#C40803",marginBottom:2}}>📅 {c.fecha}</div><div style={{fontSize:10,color:"#666"}}>📍 {c.recinto}</div>{c.notas&&<div style={{fontSize:9,color:"#444",marginTop:4,fontStyle:"italic"}}>{c.notas}</div>}</div>))}{!coberturas.length&&<div style={{textAlign:"center",padding:40,color:"#333",fontSize:12,border:"1px dashed #1a1a1a",borderRadius:10}}>🎭 Sin coberturas programadas aún.</div>}</div>)}
        {vistaCliente==="bitacora"&&(<div>{(()=>{const pubsMes=parrillas[mes]||[];const semanasMes=[...new Set(pubsMes.map(p=>p.semana))].sort((a,b)=>a-b);const conMov=pubsMes.some(p=>p.estado==="Publicado"||p.estado==="En producción");if(!conMov)return<div style={{textAlign:"center",padding:40,color:"#333",fontSize:12,border:"1px dashed #1a1a1a",borderRadius:10}}>📒 Aún no hay publicaciones registradas.</div>;return semanasMes.map(s=>{const ps=pubsMes.filter(p=>p.semana===s);const pub=ps.filter(p=>p.estado==="Publicado");const prod=ps.filter(p=>p.estado==="En producción");if(!pub.length&&!prod.length)return null;return(<div key={s} style={{marginBottom:28}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><div style={{background:"#C40803",color:"#fff",fontWeight:900,fontSize:10,padding:"4px 14px",borderRadius:6,textTransform:"uppercase"}}>Semana {s} · {etiq(s)}</div><div style={{flex:1,height:1,background:"#1a1a1a"}}/></div>{pub.length>0&&<div style={{marginBottom:10}}><div style={{fontSize:8,color:"#22c55e",fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:8,paddingLeft:4}}>✅ Publicado</div><div style={{borderLeft:"2px solid #22c55e40",paddingLeft:12,display:"flex",flexDirection:"column",gap:6}}>{pub.map(p=><div key={p.id} style={{display:"flex",alignItems:"baseline",gap:10}}><span style={{fontSize:9,color:"#555",flexShrink:0,minWidth:44}}>{p.fecha}</span><span style={{fontSize:12,color:"#ddd",fontWeight:500}}>{p.tema}</span></div>)}</div></div>}{prod.length>0&&<div><div style={{fontSize:8,color:"#3b82f6",fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:8,paddingLeft:4}}>🔵 En producción</div><div style={{borderLeft:"2px solid #3b82f640",paddingLeft:12,display:"flex",flexDirection:"column",gap:6}}>{prod.map(p=><div key={p.id} style={{display:"flex",alignItems:"baseline",gap:10}}><span style={{fontSize:9,color:"#555",flexShrink:0,minWidth:44}}>{p.fecha}</span><span style={{fontSize:12,color:"#888",fontWeight:500}}>{p.tema}</span></div>)}</div></div>}</div>);});})()}</div>)}
        <div style={{textAlign:"center",marginTop:40,fontSize:9,color:"#1a1a1a",paddingBottom:20}}>Teatrando CDMX · @teatrandocdmx · teatrando.com.mx</div>
      </div>
    </div>
  );
  return(
    <div style={{fontFamily:"Segoe UI,system-ui,sans-serif",background:"#060606",minHeight:"100vh",color:"#fff",paddingBottom:60}}>
      {notifMsg&&<div style={{position:"fixed",top:16,right:16,background:"#C40803",color:"#fff",padding:"8px 18px",borderRadius:20,fontSize:11,fontWeight:700,zIndex:9999,boxShadow:"0 4px 16px rgba(196,8,3,0.5)"}}>{notifMsg}</div>}
      {modalAgregarDia&&(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.88)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1000}}><div style={{background:"#111",border:"1px solid #C40803",borderRadius:12,padding:24,width:360,maxWidth:"90vw"}}><div style={{fontSize:14,fontWeight:700,marginBottom:14}}>➕ Agregar publicación</div>{[{l:"Fecha",k:"fecha",t:"text"},{l:"Día",k:"dia",t:"select",ops:DIAS_SEMANA},{l:"Semana #",k:"semana",t:"number"},{l:"# pubs",k:"numPubs",t:"number"}].map(f=>(<div key={f.k} style={{marginBottom:10}}><div style={{fontSize:9,color:"#555",textTransform:"uppercase",letterSpacing:1,marginBottom:3,fontWeight:700}}>{f.l}</div>{f.t==="select"?<select value={nuevoDiaForm[f.k]} onChange={e=>setNuevoDiaForm(p=>({...p,[f.k]:e.target.value}))} style={{...IS}}>{f.ops.map(o=><option key={o} style={{background:"#111"}}>{o}</option>)}</select>:<input type={f.t} value={nuevoDiaForm[f.k]} onChange={e=>setNuevoDiaForm(p=>({...p,[f.k]:e.target.value}))} style={IS}/>}</div>))}<div style={{display:"flex",gap:8,marginTop:14}}><BTN onClick={handleAgregarDia}>✅ Agregar</BTN><BTN onClick={()=>setModalAgregarDia(false)} danger>Cancelar</BTN></div></div></div>)}
      <div style={{background:"linear-gradient(135deg,#C40803 0%,#7f0000 50%,#0a0a0a 100%)",padding:"18px 20px 14px",borderBottom:"2px solid #C40803"}}>
        <div style={{maxWidth:980,margin:"0 auto"}}>
          <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:10}}>
            <div style={{display:"flex",alignItems:"center",gap:12}}><div style={{fontSize:26,fontWeight:900,color:"#fff",letterSpacing:-1}}>🎭 Teatrando</div><div><div style={{fontSize:8,color:"rgba(255,255,255,0.6)",letterSpacing:3,textTransform:"uppercase"}}>Sistema de Contenido · Admin</div><div style={{fontSize:20,fontWeight:900}}>AGOSTO 2026</div></div></div>
            <div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}>
              {[{l:"Eng/Plan/Exp",v:mix.p123,t:70},{l:"Servicio",v:mix.p4,t:20},{l:"Cult/Social",v:mix.p56,t:10}].map(m=>(<div key={m.l} style={{background:"rgba(0,0,0,0.35)",borderRadius:7,padding:"3px 9px",border:`1px solid ${Math.abs(m.v-m.t)<=5?"#22c55e":"#C40803"}40`}}><div style={{fontSize:7,color:"rgba(255,255,255,0.5)"}}>{m.l}</div><div style={{fontSize:12,fontWeight:900,color:Math.abs(m.v-m.t)<=5?"#22c55e":"#f59e0b"}}>{m.v}%<span style={{fontSize:7,opacity:0.5,marginLeft:2}}>/{m.t}%</span></div></div>))}
              <BTN onClick={doLogout} small style={{background:"rgba(0,0,0,0.4)",border:"1px solid rgba(255,255,255,0.2)"}}>👁 Vista cliente</BTN>
              <div style={{fontSize:8,display:"flex",alignItems:"center",gap:4,padding:"3px 8px",borderRadius:10,background:"rgba(0,0,0,0.3)",border:`1px solid ${syncStatus==="saved"?"#22c55e":syncStatus==="saving"?"#f59e0b":syncStatus==="error"?"#ef4444":"#222"}`}}><span style={{width:6,height:6,borderRadius:"50%",background:syncStatus==="saved"?"#22c55e":syncStatus==="saving"?"#f59e0b":syncStatus==="error"?"#ef4444":"#333",display:"inline-block"}}/><span style={{color:syncStatus==="saved"?"#22c55e":syncStatus==="saving"?"#f59e0b":syncStatus==="error"?"#ef4444":"#555"}}>{syncStatus==="saving"?"Guardando...":syncStatus==="saved"?"✓ Guardado":syncStatus==="error"?"⚠ Error":"En línea"}</span></div>
            </div>
          </div>
          <div style={{display:"flex",gap:5,marginTop:12,flexWrap:"wrap"}}>
            <BTN active={vista==="parrilla"} onClick={()=>setVista("parrilla")} small>📋 Parrilla</BTN>
            <BTN active={vista==="resenas"} onClick={()=>setVista("resenas")} small>📝 Reseñas</BTN>
            <BTN active={vista==="coberturas"} onClick={()=>setVista("coberturas")} small>🎭 Coberturas</BTN>
          </div>
        </div>
      </div>
      <div style={{maxWidth:980,margin:"0 auto",padding:"0 14px"}}>
        <div style={{marginTop:12,marginBottom:10,display:"flex",gap:6,flexWrap:"wrap",alignItems:"center"}}>{semanasDelMes.map(s=>(<button key={s} onClick={()=>{setSemanaActiva(s);setCardAbierta(null);}} style={{padding:"5px 14px",borderRadius:18,border:semanaActiva===s?"2px solid #C40803":"1.5px solid #222",background:semanaActiva===s?"#C40803":"#111",color:"#fff",fontWeight:700,cursor:"pointer",fontSize:10}}>S{s} <span style={{fontSize:9,opacity:0.6}}>({etiq(s)}) ({parrilla.filter(p=>p.semana===s).length})</span></button>))}</div>
        <div style={{background:"#0a0a12",border:"1px solid #1a1a3a",borderRadius:10,padding:"10px 14px",marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><div style={{fontSize:9,color:"#4455aa",textTransform:"uppercase",letterSpacing:1,fontWeight:700}}>📋 Línea editorial Agosto 2026</div><button onClick={()=>setEditandoBriefing(!editandoBriefing)} style={{fontSize:9,color:"#4455aa",background:"transparent",border:"1px solid #1a1a3a",borderRadius:6,padding:"2px 8px",cursor:"pointer"}}>{editandoBriefing?"✅ Listo":"✏ Editar"}</button></div>{editandoBriefing?<textarea value={briefingMes} onChange={e=>{setBriefings(prev=>{const n={...prev,[mes]:e.target.value};guardarAdmin({parrillas,resenas,briefings:n,coberturas,mesesDisp:["Agosto"]});return n;});}} rows={5} style={{width:"100%",background:"#060610",color:"#aaaadd",border:"1px solid #1a1a3a",borderRadius:7,padding:"8px 10px",fontSize:10,lineHeight:1.7,resize:"vertical",boxSizing:"border-box",fontFamily:"inherit"}}/>:<pre style={{fontSize:10,color:"#8888aa",lineHeight:1.7,whiteSpace:"pre-wrap",fontFamily:"inherit",margin:0}}>{briefingMes}</pre>}</div>
        {vista==="parrilla"&&(<><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center",marginBottom:10}}>{[{l:"Pilar",ops:["Todos",...PILARES],v:filtros.pilar,k:"pilar"},{l:"Formato",ops:["Todos","Post","Carrusel","Reel","Story"],v:filtros.formato,k:"formato"}].map(f=>(<div key={f.k} style={{display:"flex",gap:3,alignItems:"center",flexWrap:"wrap"}}><span style={{fontSize:8,color:"#333",textTransform:"uppercase",letterSpacing:1,fontWeight:700}}>{f.l}:</span>{f.ops.slice(0,6).map(o=>(<button key={o} onClick={()=>setFiltros(prev=>({...prev,[f.k]:o}))} style={{padding:"2px 7px",borderRadius:10,fontSize:8,border:f.v===o?"1.5px solid #C40803":"1px solid #1a1a1a",background:f.v===o?"#C40803":"#111",color:"#fff",cursor:"pointer",fontWeight:600}}>{o.replace("P1 – ","P1·").replace("P2 – ","P2·").replace("P3 – ","P3·").replace("P4 – ","P4·").replace("P5 – ","P5·").replace("P6 – ","P6·").replace(" estático","").replace(" interactiva","")}</button>))}</div>))}<button onClick={()=>setModalAgregarDia(true)} style={{marginLeft:"auto",padding:"4px 12px",borderRadius:16,border:"1.5px dashed #333",background:"transparent",color:"#666",cursor:"pointer",fontSize:10,fontWeight:700}}>+ Agregar día</button></div>
        <div style={{fontSize:9,color:"#333",marginBottom:8,display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}><span><span style={{color:"#C40803",fontWeight:700}}>{filtradas.length}</span> pubs · S{semanaActiva} ({etiq(semanaActiva)})</span><div style={{marginLeft:"auto",display:"flex",gap:6}}>{["Publicado","En producción","Pendiente"].map(e=>(<button key={e} onClick={()=>marcarSemana(e)} style={{padding:"3px 10px",borderRadius:12,border:`1.5px solid ${sc(e).color}50`,background:"#0a0a0a",color:sc(e).color,cursor:"pointer",fontSize:9,fontWeight:700}}>{e==="Publicado"?"✅":e==="En producción"?"🔵":"⬜"} {e}</button>))}</div></div>
        {Object.entries(byDate).map(([fecha,pubs])=>(<div key={fecha} style={{marginBottom:14}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}><div style={{background:"#C40803",color:"#fff",fontWeight:900,fontSize:9,padding:"2px 9px",borderRadius:5}}>{fecha}</div><div style={{flex:1,height:1,background:"#141414"}}/></div>{pubs.map(p=>{const isOpen=cardAbierta===p.id;const ec=sc(p.estado);return(<div key={p.id} style={{background:p.disenho==="para_disenar"?"#120000":p.disenho==="disenho_realizado"?"#001a0a":"#0b0b0b",border:isOpen?`1.5px solid ${PILAR_COLOR[p.pilar]||"#333"}`:(p.disenho==="para_disenar"?"1.5px solid #C4080350":p.disenho==="disenho_realizado"?"1.5px solid #05966950":"1px solid #141414"),borderRadius:9,marginBottom:5,overflow:"hidden"}}><div onClick={()=>setCardAbierta(isOpen?null:p.id)} style={{padding:"8px 11px",cursor:"pointer",display:"flex",alignItems:"center",gap:6,flexWrap:"wrap"}}><div style={{width:18,height:18,borderRadius:"50%",background:PILAR_COLOR[p.pilar]||"#333",display:"flex",alignItems:"center",justifyContent:"center",fontSize:8,fontWeight:900,flexShrink:0,color:"#fff"}}>{p.pub}</div>{p.tipo&&<span style={{fontSize:8,background:TIPO_COLOR[p.tipo]||"#555",color:"#fff",padding:"2px 8px",borderRadius:4,fontWeight:900,textTransform:"uppercase"}}>{p.tipo}</span>}<span style={{fontSize:7,background:PILAR_COLOR[p.pilar],color:"#fff",padding:"1px 5px",borderRadius:6,fontWeight:700}}>{p.pilar.split("–")[0].trim()}</span><span style={{fontSize:11,fontWeight:700,color:"#fff",flex:1,minWidth:100}}>{p.tema}</span>{p.disenho==="para_disenar"&&<span style={{fontSize:8,color:"#C40803"}}>🎨</span>}{p.disenho==="disenho_realizado"&&<span style={{fontSize:8,color:"#059669"}}>✅</span>}<span style={{fontSize:7,background:ec.bg,color:ec.color,padding:"1px 5px",borderRadius:6,fontWeight:700,border:`1px solid ${ec.color}30`}}>{p.estado}</span><span style={{fontSize:9,color:isOpen?"#C40803":"#222"}}>{isOpen?"▲":"▼"}</span></div>{isOpen&&(<div style={{padding:"0 11px 11px",borderTop:"1px solid #141414"}}>
        <div style={{marginTop:9,display:"flex",alignItems:"center",gap:8}}><div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,fontWeight:700,minWidth:40}}>📅 Fecha</div>{editandoFechaId===p.id?(<div style={{display:"flex",gap:6,flex:1}}><input value={nuevaFecha} onChange={e=>setNuevaFecha(e.target.value)} placeholder="ej: Mié 25" style={{...IS,width:"auto",flex:1}}/><button onClick={()=>{editarCampo(p.id,"fecha",nuevaFecha);setEditandoFechaId(null);notif("📅 Fecha actualizada");}} style={{padding:"3px 10px",borderRadius:8,background:"#C40803",color:"#fff",border:"none",cursor:"pointer",fontSize:9,fontWeight:700}}>✓</button><button onClick={()=>setEditandoFechaId(null)} style={{padding:"3px 8px",borderRadius:8,background:"#222",color:"#aaa",border:"none",cursor:"pointer",fontSize:9}}>✕</button></div>):(<div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:11,color:"#fff",fontWeight:700}}>{p.fecha}</span><button onClick={()=>{setEditandoFechaId(p.id);setNuevaFecha(p.fecha);}} style={{padding:"2px 8px",borderRadius:6,background:"#1a1a1a",color:"#666",border:"1px solid #222",cursor:"pointer",fontSize:8}}>✏ Cambiar</button></div>)}</div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:7,marginTop:9}}>{[{l:"Pilar",campo:"pilar",ops:PILARES},{l:"Formato",campo:"formato",ops:FORMATOS},{l:"Estado",campo:"estado",ops:ESTADOS}].map(f=>(<div key={f.campo}><div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,marginBottom:2,fontWeight:700}}>{f.l}</div><select value={p[f.campo]||""} onChange={e=>editarCampo(p.id,f.campo,e.target.value)} style={{...IS,background:f.campo==="estado"?ec.bg:"#0d0d0d",color:f.campo==="estado"?ec.color:"#fff",border:`1px solid ${f.campo==="estado"?ec.color+"40":"#1a1a1a"}`}}>{f.ops.map(o=><option key={o} style={{background:"#111",color:"#fff"}}>{o}</option>)}</select></div>))}</div>
        <div style={{marginTop:10,display:"flex",alignItems:"center",gap:10}}><div style={{fontSize:9,fontWeight:700,color:"#555",textTransform:"uppercase",letterSpacing:1}}>Para diseñar:</div><button onClick={()=>{const next=p.disenho===""?"para_disenar":p.disenho==="para_disenar"?"disenho_realizado":"";editarCampo(p.id,"disenho",next);}} style={{padding:"4px 16px",borderRadius:20,fontWeight:900,fontSize:10,cursor:"pointer",background:p.disenho==="para_disenar"?"#C40803":p.disenho==="disenho_realizado"?"#059669":"#0a0a0a",color:p.disenho?"#fff":"#444",border:p.disenho==="para_disenar"?"2px solid #C40803":p.disenho==="disenho_realizado"?"2px solid #059669":"1.5px solid #333",transition:"all 0.2s"}}>{p.disenho==="para_disenar"?"🎨 Para diseñar":p.disenho==="disenho_realizado"?"✅ Diseño realizado":"Enviar a diseñar"}</button></div>
        <div style={{marginTop:9}}><div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,marginBottom:3,fontWeight:700}}>Redes sociales</div><div style={{display:"flex",gap:3,flexWrap:"wrap"}}>{REDES.map(r=><button key={r} onClick={()=>toggleRed(p.id,r)} style={{padding:"2px 7px",borderRadius:8,fontSize:8,cursor:"pointer",fontWeight:600,background:(p.redes||[]).includes(r)?RED_COLOR[r]+"22":"#111",border:(p.redes||[]).includes(r)?`1.5px solid ${RED_COLOR[r]}`:"1px solid #222",color:(p.redes||[]).includes(r)?RED_COLOR[r]:"#555"}}>{RED_ICON[r]} {r}</button>)}</div></div>
        <div style={{marginTop:9}}><div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,marginBottom:2,fontWeight:700}}>Tema</div><input value={p.tema||""} onChange={e=>editarCampo(p.id,"tema",e.target.value)} style={IS}/></div>
        <div style={{marginTop:9}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:3}}><div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,fontWeight:700}}>📝 Copy</div></div><textarea value={p.copy||""} onChange={e=>editarCampo(p.id,"copy",e.target.value)} rows={5} style={{...IS,background:"#060606",lineHeight:1.65,resize:"vertical"}}/></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:7,marginTop:9}}>{[{l:"🎯 CTA",k:"cta"},{l:"🎨 Link diseño",k:"linkDiseno",ph:"https://drive.google.com/..."},{l:"🗒 Notas",k:"notas",ph:"Pendiente..."}].map(f=>(<div key={f.k}><div style={{fontSize:7,color:"#333",textTransform:"uppercase",letterSpacing:1,marginBottom:2,fontWeight:700}}>{f.l}</div><input value={p[f.k]||""} placeholder={f.ph||""} onChange={e=>editarCampo(p.id,f.k,e.target.value)} style={{...IS,background:f.k==="notas"?"#060606":"#0a0a0a",border:f.k==="notas"?"1px dashed #1a1a1a":"1px solid #1e1e1e",color:f.k==="notas"?"#666":"#fff"}}/></div>))}</div>
        <div style={{marginTop:10,display:"flex",justifyContent:"flex-end"}}><button onClick={()=>handleEliminarPub(p.id)} style={{fontSize:9,color:"#7f1d1d",background:"transparent",border:"none",cursor:"pointer"}}>🗑 Eliminar</button></div>
        </div>)}</div>);})}</div>))}</>)}
        {vista==="resenas"&&(<div style={{marginTop:12}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><div><div style={{fontSize:12,fontWeight:700}}>Reseñas — Agosto 2026</div><div style={{fontSize:9,color:"#444",marginTop:2}}>{resenasMes.length} reseñas · 10 por semana</div></div><button onClick={handleAgregarResena} style={{padding:"4px 12px",borderRadius:14,border:"1px solid #22c55e",background:"#002a10",color:"#22c55e",cursor:"pointer",fontSize:9,fontWeight:700}}>+ Nueva reseña</button></div>{[1,2].map(s=>{const rs=resenasMes.filter(r=>r.semana===s);return(<div key={s} style={{marginBottom:20}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><span style={{fontSize:8,color:"#C40803",fontWeight:700,textTransform:"uppercase",letterSpacing:2}}>Semana {s}</span><div style={{flex:1,height:1,background:"#141414"}}/><span style={{fontSize:8,color:"#333"}}>{rs.length}/10</span></div>{rs.map(r=>(<div key={r.id} style={{background:"#0b0b0b",border:"1px solid #1a1a1a",borderRadius:9,padding:"9px 12px",marginBottom:6}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:8}}><div style={{flex:1}}><input value={r.obra||""} onChange={e=>editarResena(r.id,"obra",e.target.value)} placeholder="Nombre de la obra o editorial" style={{width:"100%",background:"#111",border:"1px solid #222",borderRadius:5,padding:"3px 7px",color:"#fff",fontSize:11,marginBottom:4,fontWeight:700}}/><input value={r.titulo||""} onChange={e=>editarResena(r.id,"titulo",e.target.value)} placeholder="Título / ángulo SEO" style={{width:"100%",background:"#111",border:"1px solid #222",borderRadius:5,padding:"3px 7px",color:"#C40803",fontSize:10}}/></div><button onClick={()=>handleEliminarResena(r.id)} style={{background:"transparent",border:"none",color:"#555",cursor:"pointer",fontSize:14,padding:"2px 4px"}}>✕</button></div></div>))}{!rs.length&&<div style={{border:"1px dashed #1a1a1a",borderRadius:8,padding:"10px",textAlign:"center",color:"#333",fontSize:10}}>Sin reseñas.</div>}</div>);})}</div>)}
        {vista==="coberturas"&&(<div style={{marginTop:12}}><div style={{fontSize:12,fontWeight:700,marginBottom:4}}>Coberturas del mes — Agosto 2026</div><div style={{fontSize:9,color:"#444",marginBottom:14}}>Obras que Aarón visitará en persona este mes.</div>{coberturas.map(c=>(<div key={c.id} style={{background:"#0b0b0b",border:"1px solid #1a1a1a",borderRadius:9,padding:"12px 14px",marginBottom:8}}><div style={{display:"flex",gap:8,alignItems:"flex-start",justifyContent:"space-between"}}><div style={{flex:1}}><input value={c.obra} onChange={e=>setCoberturas(prev=>prev.map(x=>x.id===c.id?{...x,obra:e.target.value}:x))} style={{width:"100%",background:"#111",border:"1px solid #222",borderRadius:5,padding:"3px 7px",color:"#fff",fontSize:12,marginBottom:4,fontWeight:700}}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,marginTop:4}}><input value={c.fecha} onChange={e=>setCoberturas(prev=>prev.map(x=>x.id===c.id?{...x,fecha:e.target.value}:x))} placeholder="Fecha" style={{background:"#111",border:"1px solid #222",borderRadius:5,padding:"3px 7px",color:"#C40803",fontSize:10}}/><input value={c.recinto} onChange={e=>setCoberturas(prev=>prev.map(x=>x.id===c.id?{...x,recinto:e.target.value}:x))} placeholder="Recinto" style={{background:"#111",border:"1px solid #222",borderRadius:5,padding:"3px 7px",color:"#aaa",fontSize:10}}/></div><input value={c.notas} onChange={e=>setCoberturas(prev=>prev.map(x=>x.id===c.id?{...x,notas:e.target.value}:x))} placeholder="Notas..." style={{width:"100%",background:"#111",border:"1px dashed #1a1a1a",borderRadius:5,padding:"3px 7px",color:"#555",fontSize:9,marginTop:4}}/></div><button onClick={()=>setCoberturas(prev=>prev.filter(x=>x.id!==c.id))} style={{background:"transparent",border:"none",color:"#555",cursor:"pointer",fontSize:14,padding:"2px 4px"}}>✕</button></div></div>))}<button onClick={()=>setCoberturas(prev=>[...prev,{id:`cob_${Date.now()}`,obra:"Nueva cobertura",recinto:"",fecha:"",genero:"",notas:""}])} style={{padding:"6px 16px",borderRadius:14,border:"1px dashed #333",background:"transparent",color:"#555",cursor:"pointer",fontSize:10,fontWeight:700,marginTop:4}}>+ Agregar cobertura</button></div>)}
        <div style={{textAlign:"center",marginTop:28,fontSize:8,color:"#141414"}}>Teatrando CDMX · Sistema de Contenido 2026 · @teatrandocdmx</div>
      </div>
    </div>
  );
}
